package fechaappvisual;

import java.util.Calendar;
import java.util.GregorianCalendar;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    public VentanaPrincipal() {
        
        initComponents();
        this.EscribirFechaOpcion2(true);
        this.FechaOpciones.setEditable(false);
        this.MostrarFechaComparar(false);
        this.txtAviso.setVisible(false);
        this.ActivarBotones(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTituloPrograma = new javax.swing.JLabel();
        LbSeleccionalaFecha = new javax.swing.JLabel();
        FechaOpciones = new javax.swing.JComboBox<>();
        LbFecha = new javax.swing.JLabel();
        FechaSeleccionada = new javax.swing.JTextField();
        LbDia = new javax.swing.JLabel();
        EscribirDia = new javax.swing.JTextField();
        LbMes = new javax.swing.JLabel();
        EscribirMes = new javax.swing.JTextField();
        LbAño = new javax.swing.JLabel();
        EscribirAño = new javax.swing.JTextField();
        BtnAceptarFecha = new javax.swing.JButton();
        LbSumarUnDia = new javax.swing.JLabel();
        BtnSumarUnDia = new javax.swing.JButton();
        MostrarSumarUnDia = new javax.swing.JTextField();
        LbSumarVariosDias = new javax.swing.JLabel();
        CantidadNumerosSumar = new javax.swing.JTextField();
        RespuestaSumaVariosNumeros = new javax.swing.JTextField();
        BtnSumarVariosDias = new javax.swing.JButton();
        LbRestarUnDia = new javax.swing.JLabel();
        BtnRestarUnDia = new javax.swing.JButton();
        ResultadoRestarUnDia = new javax.swing.JTextField();
        BtnRestarVariosDias = new javax.swing.JLabel();
        CantidadDiasRestar = new javax.swing.JTextField();
        BtnRestarCantidadDias = new javax.swing.JButton();
        ResultadoRestarCantidadDias = new javax.swing.JTextField();
        LbAñoBisiesto = new javax.swing.JLabel();
        BtnAñoBisiesto = new javax.swing.JButton();
        SalidaAñoBisiesto = new javax.swing.JTextField();
        LBDiaDelMes = new javax.swing.JLabel();
        BtnObtenerDiaMes = new javax.swing.JButton();
        RespuestaDiasMes = new javax.swing.JTextField();
        CuadroOpcionesComparar = new javax.swing.JComboBox<>();
        ResultadoComparar = new javax.swing.JTextField();
        LbDiaComparar = new javax.swing.JLabel();
        DiasComparar = new javax.swing.JTextField();
        LbMesComparar = new javax.swing.JLabel();
        MesComparar = new javax.swing.JTextField();
        LbCompararAño = new javax.swing.JLabel();
        AñoComparar = new javax.swing.JTextField();
        BtnFechaComparar = new javax.swing.JButton();
        txtAviso = new javax.swing.JTextField();
        JlComparar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbTituloPrograma.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LbTituloPrograma.setText("FECHAS");
        LbTituloPrograma.setName("TituloApp"); // NOI18N

        LbSeleccionalaFecha.setText("Selecciona la fecha");
        LbSeleccionalaFecha.setName("TextSelecFecha"); // NOI18N

        FechaOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usar fecha del sistema", "Escribir una nueva fecha" }));
        FechaOpciones.setName("Escoger una Opción"); // NOI18N
        FechaOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaOpcionesActionPerformed(evt);
            }
        });

        LbFecha.setText("Fecha: ");

        FechaSeleccionada.setEditable(false);
        FechaSeleccionada.setText("0");
        FechaSeleccionada.setName("fecha escogida"); // NOI18N

        LbDia.setText("Dia:");

        EscribirDia.setText("0");

        LbMes.setText("Mes:");

        EscribirMes.setText("0");
        EscribirMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirMesActionPerformed(evt);
            }
        });

        LbAño.setText("Año:");

        EscribirAño.setText("0");
        EscribirAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirAñoActionPerformed(evt);
            }
        });

        BtnAceptarFecha.setText("Aceptar");
        BtnAceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarFechaActionPerformed(evt);
            }
        });

        LbSumarUnDia.setText("Sumar un día");

        BtnSumarUnDia.setText("sumar");
        BtnSumarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarUnDiaActionPerformed(evt);
            }
        });

        MostrarSumarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarSumarUnDiaActionPerformed(evt);
            }
        });

        LbSumarVariosDias.setText("Sumar varios dias");

        CantidadNumerosSumar.setText("0");

        BtnSumarVariosDias.setText("sumar");
        BtnSumarVariosDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarVariosDiasActionPerformed(evt);
            }
        });

        LbRestarUnDia.setText("Restar un día");

        BtnRestarUnDia.setText("restar");
        BtnRestarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarUnDiaActionPerformed(evt);
            }
        });

        BtnRestarVariosDias.setText("Restar varios dias");

        CantidadDiasRestar.setText("0");

        BtnRestarCantidadDias.setText("restar");
        BtnRestarCantidadDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarCantidadDiasActionPerformed(evt);
            }
        });

        ResultadoRestarCantidadDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoRestarCantidadDiasActionPerformed(evt);
            }
        });

        LbAñoBisiesto.setText("Año bisiesto");

        BtnAñoBisiesto.setText("Comprobar");
        BtnAñoBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñoBisiestoActionPerformed(evt);
            }
        });

        SalidaAñoBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaAñoBisiestoActionPerformed(evt);
            }
        });

        LBDiaDelMes.setText("Dias de mes");

        BtnObtenerDiaMes.setText("Obtener");
        BtnObtenerDiaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObtenerDiaMesActionPerformed(evt);
            }
        });

        RespuestaDiasMes.setText("0");
        RespuestaDiasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaDiasMesActionPerformed(evt);
            }
        });

        CuadroOpcionesComparar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comparar con fecha del sistema", "Comparar con una fecha escrita", "Comparar con fecha fecha constante" }));
        CuadroOpcionesComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroOpcionesCompararActionPerformed(evt);
            }
        });

        ResultadoComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoCompararActionPerformed(evt);
            }
        });

        LbDiaComparar.setText("Dia:");

        DiasComparar.setText("0");
        DiasComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasCompararActionPerformed(evt);
            }
        });

        LbMesComparar.setText("Mes:");

        MesComparar.setText("0");

        LbCompararAño.setText("año:");

        AñoComparar.setText("0");

        BtnFechaComparar.setText("aceptar");
        BtnFechaComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFechaCompararActionPerformed(evt);
            }
        });

        txtAviso.setText("Escribe o seleccina la fecha");

        JlComparar.setText("Comparación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ResultadoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(LbTituloPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CantidadDiasRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(LbRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnRestarUnDia))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CantidadNumerosSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnSumarVariosDias, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(ResultadoRestarUnDia)
                                    .addComponent(BtnRestarCantidadDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RespuestaSumaVariosNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(ResultadoRestarCantidadDias)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LBDiaDelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnObtenerDiaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalidaAñoBisiesto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RespuestaDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CuadroOpcionesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbDiaComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DiasComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(LbMesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbCompararAño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AñoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFechaComparar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbFecha)
                                        .addGap(18, 18, 18)
                                        .addComponent(FechaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnSumarUnDia)
                                        .addGap(28, 28, 28)
                                        .addComponent(MostrarSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(239, 239, 239))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbSeleccionalaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FechaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EscribirAño, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAceptarFecha)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbTituloPrograma)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSeleccionalaFecha)
                    .addComponent(FechaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDia)
                    .addComponent(EscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbMes)
                    .addComponent(EscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAño)
                    .addComponent(EscribirAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAceptarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFecha)
                    .addComponent(FechaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSumarUnDia)
                    .addComponent(BtnSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadNumerosSumar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbSumarVariosDias)
                        .addComponent(BtnSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RespuestaSumaVariosNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRestarUnDia)
                    .addComponent(BtnRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultadoRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRestarVariosDias)
                    .addComponent(CantidadDiasRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRestarCantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultadoRestarCantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAñoBisiesto)
                    .addComponent(BtnAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalidaAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBDiaDelMes)
                    .addComponent(BtnObtenerDiaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespuestaDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuadroOpcionesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDiaComparar)
                    .addComponent(DiasComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbMesComparar)
                    .addComponent(MesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCompararAño)
                    .addComponent(AñoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFechaComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultadoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlComparar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaOpcionesActionPerformed
        this.ReiniciarValores();
        if (this.FechaOpciones.getSelectedIndex() == 0 && f1 == null) {
            this.f1 = new Fecha();
            this.FechaSeleccionada.setText(f1.Imprimir());
            this.ActivarBotones(true);
        } else {
            if (this.f1 != null && this.FechaOpciones.getSelectedIndex() == 0) {
                this.f1.setAño(fecha.get(Calendar.YEAR));
                this.f1.setMes(fecha.get(Calendar.MONTH) + 1);
                this.f1.setDia(fecha.get(Calendar.DAY_OF_MONTH));
                this.FechaSeleccionada.setText(f1.Imprimir());
                this.ActivarBotones(true);
            } else {
                this.EscribirFechaOpcion2(false);
                this.BtnAceptarFecha.setEnabled(true);
            }
        }        
    }//GEN-LAST:event_FechaOpcionesActionPerformed

    private void EscribirMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirMesActionPerformed

    private void EscribirAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirAñoActionPerformed

    private void BtnAceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarFechaActionPerformed
        
        if (this.f1 == null && this.FechaOpciones.getSelectedIndex() == 1) {
            int año1 = Integer.parseInt(this.EscribirAño.getText());
            int mes1 = Integer.parseInt(this.EscribirMes.getText());
            int dia1 = Integer.parseInt(this.EscribirDia.getText());
            this.f1 = new Fecha(año1, mes1, dia1);
            this.FechaSeleccionada.setText(f1.Imprimir());
            this.EscribirFechaOpcion2(true);
        } else {
            this.f1.setAño(Integer.parseInt(this.EscribirAño.getText()));
            this.f1.setMes(Integer.parseInt(this.EscribirMes.getText()));
            this.f1.setDia(Integer.parseInt(this.EscribirDia.getText()));
            this.FechaSeleccionada.setText(f1.Imprimir());
            this.EscribirFechaOpcion2(true);
        }
        this.ActivarBotones(true);
    }//GEN-LAST:event_BtnAceptarFechaActionPerformed

    private void MostrarSumarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarSumarUnDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarSumarUnDiaActionPerformed

    private void BtnSumarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarUnDiaActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            this.f1.IncrementaDia();
            this.MostrarSumarUnDia.setText(this.f1.Imprimir());
            this.FechaSeleccionada.setText(this.f1.Imprimir());
        } else {
            this.txtAviso.setVisible(true);
        }
    }//GEN-LAST:event_BtnSumarUnDiaActionPerformed

    private void BtnSumarVariosDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarVariosDiasActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            this.f1.IncrementaDia(Integer.parseInt(this.CantidadNumerosSumar.getText()));
            this.MostrarSumarUnDia.setText(this.f1.Imprimir());
            this.RespuestaSumaVariosNumeros.setText(this.f1.Imprimir());
            this.FechaSeleccionada.setText(this.f1.Imprimir());
        }
    }//GEN-LAST:event_BtnSumarVariosDiasActionPerformed

    private void BtnRestarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarUnDiaActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            this.f1.DecrementaDia();
            this.MostrarSumarUnDia.setText(this.f1.Imprimir());
            this.RespuestaSumaVariosNumeros.setText(this.f1.Imprimir());
            this.ResultadoRestarUnDia.setText(this.f1.Imprimir());
            this.FechaSeleccionada.setText(this.f1.Imprimir());
        }
    }//GEN-LAST:event_BtnRestarUnDiaActionPerformed

    private void ResultadoRestarCantidadDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoRestarCantidadDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoRestarCantidadDiasActionPerformed

    private void BtnRestarCantidadDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarCantidadDiasActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            this.f1.DecrementaDia(Integer.parseInt(this.CantidadDiasRestar.getText()));
            this.MostrarSumarUnDia.setText(this.f1.Imprimir());
            this.RespuestaSumaVariosNumeros.setText(this.f1.Imprimir());
            this.ResultadoRestarUnDia.setText(this.f1.Imprimir());
            this.FechaSeleccionada.setText(this.f1.Imprimir());
            this.ResultadoRestarCantidadDias.setText(this.f1.Imprimir());
        }
    }//GEN-LAST:event_BtnRestarCantidadDiasActionPerformed

    private void SalidaAñoBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaAñoBisiestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaAñoBisiestoActionPerformed

    private void BtnAñoBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñoBisiestoActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            if (this.f1.Bisiesto(this.f1.getAño()) == true) {
                this.SalidaAñoBisiesto.setText("El año es bisiesto");
            } else {
                this.SalidaAñoBisiesto.setText("El año no es bisiesto");
            }
        }
    }//GEN-LAST:event_BtnAñoBisiestoActionPerformed

    private void BtnObtenerDiaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObtenerDiaMesActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            int diasMes = this.f1.DiaMes(this.f1.getMes());
            this.RespuestaDiasMes.setText(diasMes + " Dias");
        }
    }//GEN-LAST:event_BtnObtenerDiaMesActionPerformed

    private void RespuestaDiasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaDiasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaDiasMesActionPerformed

    private void ResultadoCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoCompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoCompararActionPerformed

    private void CuadroOpcionesCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroOpcionesCompararActionPerformed
        if (this.FechaSeleccionada.getText().length() > 0) {
            if (this.CuadroOpcionesComparar.getSelectedIndex() == 0) {
                if (this.f2 == null) {
                    this.f2 = new Fecha();
                    this.CompararFechas();
                } else {
                    this.CompararFechas();
                }
            } else {
                if (this.CuadroOpcionesComparar.getSelectedIndex() == 1) {
                    this.MostrarFechaComparar(true);
                } else {
                    if (this.f2 == null) {
                        this.f2 = new Fecha(2000, 1, 1);
                        this.CompararFechas();
                    } else {
                        this.CompararFechas();
                    }
                }
            }
        }
    }//GEN-LAST:event_CuadroOpcionesCompararActionPerformed

    private void DiasCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasCompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasCompararActionPerformed

    private void BtnFechaCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFechaCompararActionPerformed
        int año = Integer.parseInt(this.AñoComparar.getText());
        int mes = Integer.parseInt(this.MesComparar.getText());
        int dia = Integer.parseInt(this.DiasComparar.getText());
        if (this.f2 == null) {
            this.f2 = new Fecha(año, mes, dia);
            this.CompararFechas();
        } else {
            this.f2.setAño(año);
            this.f2.setMes(mes);
            this.f2.setDia(dia);
            this.CompararFechas();
        }
        this.MostrarFechaComparar(false);
    }//GEN-LAST:event_BtnFechaCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void ActivarBotones(boolean activar) {
        
        this.BtnAceptarFecha.setEnabled(activar);
        this.BtnAñoBisiesto.setEnabled(activar);
        this.BtnFechaComparar.setEnabled(activar);
        this.BtnObtenerDiaMes.setEnabled(activar);
        this.BtnRestarCantidadDias.setEnabled(activar);
        this.BtnRestarUnDia.setEnabled(activar);
        this.BtnRestarVariosDias.setEnabled(activar);
        this.BtnSumarUnDia.setEnabled(activar);
        this.BtnSumarUnDia.setEnabled(activar);
        this.BtnSumarVariosDias.setEnabled(activar);
        this.CuadroOpcionesComparar.setEnabled(activar);
    }
    
    public void CompararFechas() {
        this.f2 = new Fecha();
        if (this.f2.Comparar(this.f1.getAño(), this.f1.getMes(), this.f1.getDia()) == 1) {
            this.ResultadoComparar.setText("La fecha es mayor que la del sistema");
        } else {
            if (this.f2.Comparar(this.f1.getAño(), this.f1.getMes(), this.f1.getDia()) == -1) {
                this.ResultadoComparar.setText("La fecha es menor que la del sistema");
            } else {
                this.ResultadoComparar.setText("La fecha es igual que la del sistema");
            }
        }
    }
    
    public void EscribirFechaOpcion2(boolean ocultar) {
        if (ocultar == true) {
            this.LbAño.setVisible(false);
            this.LbMes.setVisible(false);
            this.LbDia.setVisible(false);
            this.EscribirAño.setVisible(false);
            this.EscribirMes.setVisible(false);
            this.EscribirDia.setVisible(false);
            this.BtnAceptarFecha.setVisible(false);
        } else {
            this.LbAño.setVisible(true);
            this.LbMes.setVisible(true);
            this.LbDia.setVisible(true);
            this.EscribirAño.setVisible(true);
            this.EscribirMes.setVisible(true);
            this.EscribirDia.setVisible(true);
            this.BtnAceptarFecha.setVisible(true);
        }
    }
    
    public void MostrarFechaComparar(boolean mostrar) {
        if (mostrar == true) {
            this.LbCompararAño.setVisible(true);
            this.LbMesComparar.setVisible(true);
            this.LbDiaComparar.setVisible(true);
            this.DiasComparar.setVisible(true);
            this.MesComparar.setVisible(true);
            this.AñoComparar.setVisible(true);
            this.BtnFechaComparar.setVisible(true);
        } else {
            this.LbCompararAño.setVisible(false);
            this.LbMesComparar.setVisible(false);
            this.LbDiaComparar.setVisible(false);
            this.DiasComparar.setVisible(false);
            this.MesComparar.setVisible(false);
            this.AñoComparar.setVisible(false);
            this.BtnFechaComparar.setVisible(false);
        }
    }
    
    public void ReiniciarValores() {
        this.SalidaAñoBisiesto.setText("");
        this.RespuestaSumaVariosNumeros.setText("");
        this.ResultadoRestarCantidadDias.setText("");
        this.ResultadoComparar.setText("");
        this.MostrarSumarUnDia.setText("");
        this.ResultadoRestarUnDia.setText("");
        this.RespuestaDiasMes.setText("");
    }
    
    Calendar fecha = new GregorianCalendar();
    Fecha f1, f2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñoComparar;
    private javax.swing.JButton BtnAceptarFecha;
    private javax.swing.JButton BtnAñoBisiesto;
    private javax.swing.JButton BtnFechaComparar;
    private javax.swing.JButton BtnObtenerDiaMes;
    private javax.swing.JButton BtnRestarCantidadDias;
    private javax.swing.JButton BtnRestarUnDia;
    private javax.swing.JLabel BtnRestarVariosDias;
    private javax.swing.JButton BtnSumarUnDia;
    private javax.swing.JButton BtnSumarVariosDias;
    private javax.swing.JTextField CantidadDiasRestar;
    private javax.swing.JTextField CantidadNumerosSumar;
    private javax.swing.JComboBox<String> CuadroOpcionesComparar;
    private javax.swing.JTextField DiasComparar;
    private javax.swing.JTextField EscribirAño;
    private javax.swing.JTextField EscribirDia;
    private javax.swing.JTextField EscribirMes;
    private javax.swing.JComboBox<String> FechaOpciones;
    private javax.swing.JTextField FechaSeleccionada;
    private javax.swing.JLabel JlComparar;
    private javax.swing.JLabel LBDiaDelMes;
    private javax.swing.JLabel LbAño;
    private javax.swing.JLabel LbAñoBisiesto;
    private javax.swing.JLabel LbCompararAño;
    private javax.swing.JLabel LbDia;
    private javax.swing.JLabel LbDiaComparar;
    private javax.swing.JLabel LbFecha;
    private javax.swing.JLabel LbMes;
    private javax.swing.JLabel LbMesComparar;
    private javax.swing.JLabel LbRestarUnDia;
    private javax.swing.JLabel LbSeleccionalaFecha;
    private javax.swing.JLabel LbSumarUnDia;
    private javax.swing.JLabel LbSumarVariosDias;
    private javax.swing.JLabel LbTituloPrograma;
    private javax.swing.JTextField MesComparar;
    private javax.swing.JTextField MostrarSumarUnDia;
    private javax.swing.JTextField RespuestaDiasMes;
    private javax.swing.JTextField RespuestaSumaVariosNumeros;
    private javax.swing.JTextField ResultadoComparar;
    private javax.swing.JTextField ResultadoRestarCantidadDias;
    private javax.swing.JTextField ResultadoRestarUnDia;
    private javax.swing.JTextField SalidaAñoBisiesto;
    private javax.swing.JTextField txtAviso;
    // End of variables declaration//GEN-END:variables
}
