/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quicksortvisual;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author ALEXIS
 */
public class QuickV extends javax.swing.JFrame {

    /**
     * Creates new form QuickV
     */
    
    ArrayList<Integer> lista = new ArrayList<>();
    int items=0;
    int lt[];
    
    
    public QuickV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsercion = new javax.swing.JRadioButton();
        txtnum = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txanum = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txapasadas = new javax.swing.JTextArea();
        Quicksort = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsercion.setText("Insercion");
        btnInsercion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsercionMouseClicked(evt);
            }
        });
        btnInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txanum.setColumns(20);
        txanum.setRows(5);
        jScrollPane1.setViewportView(txanum);

        txapasadas.setColumns(20);
        txapasadas.setRows(5);
        jScrollPane2.setViewportView(txapasadas);

        Quicksort.setText("Quicksort");
        Quicksort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuicksortMouseClicked(evt);
            }
        });
        Quicksort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuicksortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Quicksort)
                        .addGap(88, 88, 88)
                        .addComponent(btnInsercion))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAgregar)
                    .addComponent(Quicksort)
                    .addComponent(btnInsercion))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (!txtnum.getText().equals("")) {
            lista.add(Integer.parseInt(txtnum.getText().toString()));
            txtnum.setText("");
            txtnum.requestFocus();
            Visualizar();
        } else {
            JOptionPane.showMessageDialog(null, "Inserta valores a la lista");
        }
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void QuicksortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuicksortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuicksortActionPerformed

    private void QuicksortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuicksortMouseClicked
        // TODO add your handling code here:
        if (!txanum.getText().equals("")) {
            items=0;
            txapasadas.setText("");
            Quicksort();
            
        }else{
            JOptionPane.showMessageDialog(null,"Insertar Valores" );
        }
    }//GEN-LAST:event_QuicksortMouseClicked

    private void btnInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsercionActionPerformed

    private void btnInsercionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsercionMouseClicked
        // TODO add your handling code here:
        if (!txanum.getText().equals("")) {
            items=0;
            txapasadas.setText("");
            Insercion();
        }else{
            JOptionPane.showMessageDialog(null, "Inseta Valores");
        }
    }//GEN-LAST:event_btnInsercionMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        lista.clear();
        txtnum.setText("");
        txanum.setText("");
        items=0;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void Visualizar() {
        txanum.setText("");
        String list = "";
        for (int i = 0; i < lista.size(); i++) {
            list += lista.get(i) + "\n";
        }
        txanum.setText(list);
    }
    public int[] transformar() {
        Object numeros[] = new Object[lista.size()];
        numeros = lista.toArray();
        int n[] = new int[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            n[i] = Integer.parseInt(numeros[i].toString());
        }
        return n;
    }
    public void ImprimirLista() {
        items++;
        String r = items + "->";
        for (int i = 0; i < lt.length; i++) {
            r = r + lt[i] + "-";
        }
        txapasadas.append(r+"\n");
        
    }
    public void Quicksort(){
       lt=transformar();
        for (int i = 0; i < lt.length-1; i++) {
            ImprimirLista();
            OrdenarQuicksort(lt, 0, lt.length-1);
        }
    }
    public static void OrdenarQuicksort(int[] vector, int primero, int ultimo) {

        int i = primero;
        int j = ultimo;
        int pivote = vector[(primero + ultimo) / 2];
        int aux;
        do {

            while (vector[i] < pivote) {
                i++;
            }
            while (vector[j] > pivote) {
                j--;
            }
            if (i <= j) {
                aux = vector[j];
                vector[j] = vector[i];
                vector[i] = aux;
                i++;
                j--;
            }
        } while (i <= j);
        if (primero < j) {
            OrdenarQuicksort(vector, primero, j);
        }
        if (ultimo > i) {
            OrdenarQuicksort(vector, i, ultimo);
        }

    }
    public void Insercion(){
        int cont=0;
        int d = 0;
        int dat;
        lt=transformar();
        ImprimirLista();
        for (int j = 1; j < lt.length ; j++) {
            dat = lt[j];
            int i = j-1;
            while (i>=0 && lt[i]>dat) {                
                lt[i+1]=lt[i];
                i--;
                cont=cont+1;
                ImprimirLista();
            }
            lt[i+1]=dat;
            d= cont;
            ImprimirLista();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Quicksort;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JRadioButton btnInsercion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txanum;
    private javax.swing.JTextArea txapasadas;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
