/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appfecha;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.ActivarBotones(false);
        this.MostrarEscribirFecha(false);
        this.MostrarEscribirFechaComparar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnPresentacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LbUniversidad = new javax.swing.JLabel();
        LbCurso = new javax.swing.JLabel();
        LbEstudiante = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LbEscribirSeleccionarFecha = new javax.swing.JLabel();
        CbEscogerFecha = new javax.swing.JComboBox<>();
        LbDia = new javax.swing.JLabel();
        TxtDia = new javax.swing.JTextField();
        LbMes = new javax.swing.JLabel();
        TxtMes = new javax.swing.JTextField();
        LbAño = new javax.swing.JLabel();
        TxtAño = new javax.swing.JTextField();
        BtnAceptarFecha = new javax.swing.JButton();
        LbFecha = new javax.swing.JLabel();
        TxtFechaSeleccionada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LbSumarUnDia = new javax.swing.JLabel();
        BtnSumarUnDia = new javax.swing.JButton();
        TxtSumarUnDia = new javax.swing.JTextField();
        LbSumarVariosDias = new javax.swing.JLabel();
        TxtCantidadSumarVariosDias = new javax.swing.JTextField();
        BtnSumarVariosDias = new javax.swing.JButton();
        TxtSumarVariosDias = new javax.swing.JTextField();
        LbRestarUnDia = new javax.swing.JLabel();
        BtnRestarUnDia = new javax.swing.JButton();
        TxtRestarUnDia = new javax.swing.JTextField();
        LbRestarVariosDias = new javax.swing.JLabel();
        TxtCantidadRestarVariosDias = new javax.swing.JTextField();
        BtnRestarVariosDias = new javax.swing.JButton();
        TxtRestarVariosDias = new javax.swing.JTextField();
        LbAñoBisiesto = new javax.swing.JLabel();
        BtnAñoBisiesto = new javax.swing.JButton();
        TxtDiasMes = new javax.swing.JTextField();
        LbDiasMes = new javax.swing.JLabel();
        BtnDiasMes = new javax.swing.JButton();
        TxtAñoBisiesto = new javax.swing.JTextField();
        CbOpcionesCompararFecha = new javax.swing.JComboBox<>();
        LbDiaComparar = new javax.swing.JLabel();
        TxtDiaComparar = new javax.swing.JTextField();
        LbMesComparar = new javax.swing.JLabel();
        TxtMesComparar = new javax.swing.JTextField();
        LbAñoComparar = new javax.swing.JLabel();
        TxtAñoComparar = new javax.swing.JTextField();
        BtnComparar = new javax.swing.JButton();
        LbComparar = new javax.swing.JLabel();
        TxtComparar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("FECHA");

        LbUniversidad.setText("Universidad Técnica del Norte");

        LbCurso.setText("Programación Orientada a Objetos");

        LbEstudiante.setText("Ramírez Henry");

        javax.swing.GroupLayout PnPresentacionLayout = new javax.swing.GroupLayout(PnPresentacion);
        PnPresentacion.setLayout(PnPresentacionLayout);
        PnPresentacionLayout.setHorizontalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbUniversidad)
                .addContainerGap())
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnPresentacionLayout.setVerticalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LbUniversidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbEstudiante))
        );

        LbEscribirSeleccionarFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        LbEscribirSeleccionarFecha.setText("Selecciona la fecha");

        CbEscogerFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usar fecha del sistema", "Escribir una nueva fecha" }));
        CbEscogerFecha.setName("Escoger una Opción"); // NOI18N
        CbEscogerFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbEscogerFechaActionPerformed(evt);
            }
        });

        LbDia.setText("Dia:");

        TxtDia.setText("0");

        LbMes.setText("Mes:");

        TxtMes.setText("0");
        TxtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMesActionPerformed(evt);
            }
        });

        LbAño.setText("Año:");

        TxtAño.setText("0");
        TxtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAñoActionPerformed(evt);
            }
        });

        BtnAceptarFecha.setText("Aceptar");
        BtnAceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarFechaActionPerformed(evt);
            }
        });

        LbFecha.setText("Fecha: ");

        TxtFechaSeleccionada.setEditable(false);
        TxtFechaSeleccionada.setText("0-0-0");
        TxtFechaSeleccionada.setName("fecha escogida"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbEscribirSeleccionarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbEscogerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(BtnAceptarFecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbFecha)
                        .addGap(18, 18, 18)
                        .addComponent(TxtFechaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbEscogerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEscribirSeleccionarFecha)
                    .addComponent(LbDia)
                    .addComponent(TxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbMes)
                    .addComponent(TxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAño)
                    .addComponent(TxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAceptarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFecha)
                    .addComponent(TxtFechaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbSumarUnDia.setText("Sumar un día");

        BtnSumarUnDia.setText("sumar");
        BtnSumarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarUnDiaActionPerformed(evt);
            }
        });

        TxtSumarUnDia.setText("0-0-0");
        TxtSumarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSumarUnDiaActionPerformed(evt);
            }
        });

        LbSumarVariosDias.setText("Sumar varios dias");

        TxtCantidadSumarVariosDias.setText("0");

        BtnSumarVariosDias.setText("sumar");
        BtnSumarVariosDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarVariosDiasActionPerformed(evt);
            }
        });

        TxtSumarVariosDias.setText("0-0-0");

        LbRestarUnDia.setText("Restar un día");

        BtnRestarUnDia.setText("restar");
        BtnRestarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarUnDiaActionPerformed(evt);
            }
        });

        TxtRestarUnDia.setText("0-0-0");

        LbRestarVariosDias.setText("Restar varios dias");

        TxtCantidadRestarVariosDias.setText("0");

        BtnRestarVariosDias.setText("restar");
        BtnRestarVariosDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarVariosDiasActionPerformed(evt);
            }
        });

        TxtRestarVariosDias.setText("0-0-0");

        LbAñoBisiesto.setText("Año bisiesto");

        BtnAñoBisiesto.setText("Comprobar");
        BtnAñoBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñoBisiestoActionPerformed(evt);
            }
        });

        TxtDiasMes.setText("...");
        TxtDiasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiasMesActionPerformed(evt);
            }
        });

        LbDiasMes.setText("Dias de mes");

        BtnDiasMes.setText("Comprobar");
        BtnDiasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiasMesActionPerformed(evt);
            }
        });

        TxtAñoBisiesto.setText("...");
        TxtAñoBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAñoBisiestoActionPerformed(evt);
            }
        });

        CbOpcionesCompararFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comparar con fecha del sistema", "Comparar con una fecha escrita", "Comparar con fecha constante" }));
        CbOpcionesCompararFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbOpcionesCompararFechaActionPerformed(evt);
            }
        });

        LbDiaComparar.setText("Dia:");

        TxtDiaComparar.setText("0");
        TxtDiaComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiaCompararActionPerformed(evt);
            }
        });

        LbMesComparar.setText("Mes:");

        TxtMesComparar.setText("0");

        LbAñoComparar.setText("año:");

        TxtAñoComparar.setText("0");

        BtnComparar.setText("Comparar");
        BtnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompararActionPerformed(evt);
            }
        });

        LbComparar.setText("Comparación");

        TxtComparar.setText("...");
        TxtComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCompararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LbSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addComponent(BtnSumarUnDia)
                            .addGap(18, 18, 18)
                            .addComponent(TxtSumarUnDia, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(LbRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtCantidadRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(LbSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(TxtCantidadSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(LbRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnRestarUnDia)
                                .addComponent(BtnSumarVariosDias)
                                .addComponent(BtnRestarVariosDias))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtSumarVariosDias)
                                .addComponent(TxtRestarUnDia)
                                .addComponent(TxtRestarVariosDias))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LbComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtComparar))
                            .addComponent(CbOpcionesCompararFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbDiaComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDiaComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbMesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbAñoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAñoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSumarUnDia)
                    .addComponent(BtnSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSumarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSumarVariosDias)
                    .addComponent(TxtCantidadSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSumarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRestarUnDia)
                    .addComponent(BtnRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRestarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRestarVariosDias)
                    .addComponent(TxtCantidadRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRestarVariosDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAñoBisiesto)
                    .addComponent(BtnAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAñoBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDiasMes)
                    .addComponent(BtnDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbOpcionesCompararFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDiaComparar)
                    .addComponent(TxtDiaComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbMesComparar)
                    .addComponent(TxtMesComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAñoComparar)
                    .addComponent(TxtAñoComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbComparar)
                    .addComponent(TxtComparar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CbEscogerFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbEscogerFechaActionPerformed
        this.ActivarBotones(false);
        this.ReiniciarValores();
        if (this.CbEscogerFecha.getSelectedIndex() == 0 && f1 == null) {
            this.f1 = new Fecha();
            this.TxtFechaSeleccionada.setText(f1.Imprimir());
            this.ActivarBotones(true);
        } else {
            if (this.f1 != null && this.CbEscogerFecha.getSelectedIndex() == 0) {
                this.f1.setAño(fecha.get(Calendar.YEAR));
                this.f1.setMes(fecha.get(Calendar.MONTH) + 1);
                this.f1.setDia(fecha.get(Calendar.DAY_OF_MONTH));
                this.TxtFechaSeleccionada.setText(f1.Imprimir());
                this.ActivarBotones(true);
            } else {
                this.MostrarEscribirFecha(true);
            }
        }
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_CbEscogerFechaActionPerformed

    private void TxtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMesActionPerformed

    private void TxtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAñoActionPerformed

    private void BtnAceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarFechaActionPerformed
        if (this.f1 == null && this.CbEscogerFecha.getSelectedIndex() == 1) {
            int año1 = Integer.parseInt(this.TxtAño.getText());
            int mes1 = Integer.parseInt(this.TxtMes.getText());
            int dia1 = Integer.parseInt(this.TxtDia.getText());
            this.f1 = new Fecha(año1, mes1, dia1);
            this.TxtFechaSeleccionada.setText(f1.Imprimir());
            this.MostrarEscribirFecha(false);
        } else {
            this.f1.setAño(Integer.parseInt(this.TxtAño.getText()));
            this.f1.setMes(Integer.parseInt(this.TxtMes.getText()));
            this.f1.setDia(Integer.parseInt(this.TxtDia.getText()));
            this.TxtFechaSeleccionada.setText(f1.Imprimir());
            this.MostrarEscribirFecha(false);
        }
        this.ActivarBotones(true);
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_BtnAceptarFechaActionPerformed

    private void BtnSumarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarUnDiaActionPerformed
        this.f1.IncrementaDia();
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_BtnSumarUnDiaActionPerformed

    private void TxtSumarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSumarUnDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSumarUnDiaActionPerformed

    private void BtnSumarVariosDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarVariosDiasActionPerformed
        this.f1.IncrementaDia(Integer.parseInt(this.TxtCantidadSumarVariosDias.getText()));
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_BtnSumarVariosDiasActionPerformed

    private void BtnRestarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarUnDiaActionPerformed
        this.f1.DecrementaDia();
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_BtnRestarUnDiaActionPerformed

    private void BtnRestarVariosDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarVariosDiasActionPerformed
        this.f1.DecrementaDia(Integer.parseInt(this.TxtCantidadRestarVariosDias.getText()));
        this.TxtFechaSeleccionada.setText(this.f1.Imprimir());
        this.TxtSumarUnDia.setText(this.f1.Imprimir());
        this.TxtSumarVariosDias.setText(this.f1.Imprimir());
        this.TxtRestarUnDia.setText(this.f1.Imprimir());
        this.TxtRestarVariosDias.setText(this.f1.Imprimir());
    }//GEN-LAST:event_BtnRestarVariosDiasActionPerformed

    private void BtnAñoBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñoBisiestoActionPerformed
        if (this.f1.Bisiesto(this.f1.getAño()) == true) {
            this.TxtAñoBisiesto.setText("El año es bisiesto");
        } else {
            this.TxtAñoBisiesto.setText("El año no es bisiesto");
        }
    }//GEN-LAST:event_BtnAñoBisiestoActionPerformed

    private void TxtDiasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiasMesActionPerformed

    private void BtnDiasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiasMesActionPerformed
        this.TxtDiasMes.setText(this.f1.DiaMes(this.f1.getMes()) + " dias");
    }//GEN-LAST:event_BtnDiasMesActionPerformed

    private void TxtAñoBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAñoBisiestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAñoBisiestoActionPerformed

    private void CbOpcionesCompararFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbOpcionesCompararFechaActionPerformed
        if (this.CbOpcionesCompararFecha.getSelectedIndex() == 0) {
            this.CompararFechas(this.f1.Comparar(fecha.get(Calendar.YEAR), fecha.get(Calendar.MONTH) + 1, fecha.get(Calendar.DAY_OF_MONTH)));
        } else {
            if (this.CbOpcionesCompararFecha.getSelectedIndex() == 1) {
                this.MostrarEscribirFechaComparar(true);
            } else {
                this.CompararFechas(this.f1.Comparar(2002, 23, 1));
            }
        }
    }//GEN-LAST:event_CbOpcionesCompararFechaActionPerformed

    private void TxtDiaCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiaCompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiaCompararActionPerformed

    private void BtnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompararActionPerformed
        if (this.f2 == null) {
            this.f2 = new Fecha(Integer.parseInt(this.TxtAñoComparar.getText()), Integer.parseInt(this.TxtMesComparar.getText()), Integer.parseInt(this.TxtDiaComparar.getText()));
            this.CompararFechas(this.f1.Comparar(f2));
        } else {
            this.f2.setAño(Integer.parseInt(this.TxtAñoComparar.getText()));
            this.f2.setMes(Integer.parseInt(this.TxtMesComparar.getText()));
            this.f2.setMes(Integer.parseInt(this.TxtDiaComparar.getText()));
            this.CompararFechas(this.f1.Comparar(f2));
        }
        this.MostrarEscribirFechaComparar(false);
    }//GEN-LAST:event_BtnCompararActionPerformed

    private void TxtCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCompararActionPerformed

    public void CompararFechas(int respuesta) {
        respuesta *= -1;
        if (respuesta == 1) {
            this.TxtComparar.setText("La fecha es mayor");
        } else {
            if (respuesta == -1) {
                this.TxtComparar.setText("La fecha es menor");
            } else {
                this.TxtComparar.setText("Fechas iguales");
            }
        }
    }

    public void MostrarEscribirFechaComparar(boolean mostrar) {
        this.LbAñoComparar.setVisible(mostrar);
        this.LbMesComparar.setVisible(mostrar);
        this.LbDiaComparar.setVisible(mostrar);
        this.TxtAñoComparar.setVisible(mostrar);
        this.TxtMesComparar.setVisible(mostrar);
        this.TxtDiaComparar.setVisible(mostrar);
        this.BtnComparar.setVisible(mostrar);
    }

    public void MostrarEscribirFecha(boolean mostrar) {
        this.LbAño.setVisible(mostrar);
        this.LbMes.setVisible(mostrar);
        this.LbDia.setVisible(mostrar);
        this.TxtAño.setVisible(mostrar);
        this.TxtMes.setVisible(mostrar);
        this.TxtDia.setVisible(mostrar);
        this.BtnAceptarFecha.setVisible(mostrar);
    }

    public void ActivarBotones(boolean activar) {
        this.BtnAñoBisiesto.setEnabled(activar);
        this.BtnDiasMes.setEnabled(activar);
        this.BtnRestarUnDia.setEnabled(activar);
        this.BtnRestarVariosDias.setEnabled(activar);
        this.BtnSumarUnDia.setEnabled(activar);
        this.BtnSumarVariosDias.setEnabled(activar);
        this.CbOpcionesCompararFecha.setEnabled(activar);
    }

    public void ReiniciarValores() {
        this.TxtSumarUnDia.setText("0-0-0");
        this.TxtSumarVariosDias.setText("0-0-0");
        this.TxtRestarUnDia.setText("0-0-0");
        this.TxtRestarVariosDias.setText("0-0-0");
        this.TxtCantidadRestarVariosDias.setText("0");
        this.TxtCantidadSumarVariosDias.setText("0");
        this.TxtFechaSeleccionada.setText("0-0-0");
        this.TxtAñoBisiesto.setText("...");
        this.TxtDiasMes.setText("...");
        this.TxtComparar.setText("...");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    Calendar fecha = new GregorianCalendar();
    Fecha f1, f2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarFecha;
    private javax.swing.JButton BtnAñoBisiesto;
    private javax.swing.JButton BtnComparar;
    private javax.swing.JButton BtnDiasMes;
    private javax.swing.JButton BtnRestarUnDia;
    private javax.swing.JButton BtnRestarVariosDias;
    private javax.swing.JButton BtnSumarUnDia;
    private javax.swing.JButton BtnSumarVariosDias;
    private javax.swing.JComboBox<String> CbEscogerFecha;
    private javax.swing.JComboBox<String> CbOpcionesCompararFecha;
    private javax.swing.JLabel LbAño;
    private javax.swing.JLabel LbAñoBisiesto;
    private javax.swing.JLabel LbAñoComparar;
    private javax.swing.JLabel LbComparar;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbDia;
    private javax.swing.JLabel LbDiaComparar;
    private javax.swing.JLabel LbDiasMes;
    private javax.swing.JLabel LbEscribirSeleccionarFecha;
    private javax.swing.JLabel LbEstudiante;
    private javax.swing.JLabel LbFecha;
    private javax.swing.JLabel LbMes;
    private javax.swing.JLabel LbMesComparar;
    private javax.swing.JLabel LbRestarUnDia;
    private javax.swing.JLabel LbRestarVariosDias;
    private javax.swing.JLabel LbSumarUnDia;
    private javax.swing.JLabel LbSumarVariosDias;
    private javax.swing.JLabel LbUniversidad;
    private javax.swing.JPanel PnPresentacion;
    private javax.swing.JTextField TxtAño;
    private javax.swing.JTextField TxtAñoBisiesto;
    private javax.swing.JTextField TxtAñoComparar;
    private javax.swing.JTextField TxtCantidadRestarVariosDias;
    private javax.swing.JTextField TxtCantidadSumarVariosDias;
    private javax.swing.JTextField TxtComparar;
    private javax.swing.JTextField TxtDia;
    private javax.swing.JTextField TxtDiaComparar;
    private javax.swing.JTextField TxtDiasMes;
    private javax.swing.JTextField TxtFechaSeleccionada;
    private javax.swing.JTextField TxtMes;
    private javax.swing.JTextField TxtMesComparar;
    private javax.swing.JTextField TxtRestarUnDia;
    private javax.swing.JTextField TxtRestarVariosDias;
    private javax.swing.JTextField TxtSumarUnDia;
    private javax.swing.JTextField TxtSumarVariosDias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
