    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejo_de_estructuras_tipo_pilas_y_colas_de_objetos;

import Coordenadas_polares_y_rectangulares.Coordenadas_polares;
import Coordenadas_polares_y_rectangulares.Coordenadas_rectangulares;
import Cuenta_Bancaria.Cuenta;
import Fecha.Fecha;
import Figuras_Geometricasa.Circunferencia;
import Figuras_Geometricasa.Cuadrado;
import Figuras_Geometricasa.Elipse;
import Figuras_Geometricasa.Figura_geometrica;
import Figuras_Geometricasa.Recta;
import Figuras_Geometricasa.Rectangulo;
import Figuras_Geometricasa.Triangulo;
import Fraccionario.Fraccionario;
import Fraccionario.Mixto;
import NumerosComplejos.NumerosComplejos;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin
 */
public class Principal extends javax.swing.JFrame {
    //Ventanas

    Ventana_Figuras_Geometrica ventana_Figuras_Geometrica;
    Ventana_Cuenta_Bancaria ventana_Cuenta_Bancaria;
    Ventana_Numeros_Complejos ventana_Numeros_Complejos;
    Ventana_Fecha ventana_Fecha;
    Ventana_Coordenadas ventana_Coordenadas;
    Ventana_Fraccionario ventana_Fraccionario;

    //Rutas
    String ruta_figura;
    String ruta_cuenta;
    String ruta_numerosComplejos;
    String ruta_fecha;
    String ruta_Coordenadas;
    String ruta_Fraccion;

    //Pilas
    Pila pila_figuras;
    Pila pila_cuenta;
    Pila pila_numerosComplejos;
    Pila pila_fecha;
    Pila pila_Coordenadas;
    Pila pila_fraccionario;

    //--------
    Pila pila_principal;

    //------------
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ruta_figura = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaFigurasGeometricas.txt";
        ruta_cuenta = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaCuenta.txt";
        ruta_numerosComplejos = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaNumComplejos.txt";
        ruta_fecha = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaFecha.txt";
        ruta_Coordenadas = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaCoordenadas.txt";
        ruta_Fraccion = "C:/Users/ALEXIS/Desktop/Manejo_de_estructuras_tipo_pilas_y_colas_de_objetos/serializacion/PilaFraccion.txt";

        pila_principal = new Pila();

        setLocationRelativeTo(null);
        // tabla_pila.setValueAt("Hola", 1, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Figuras_Geometrica = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        lbl_figuras = new javax.swing.JLabel();
        btn_cuenta = new javax.swing.JButton();
        lbl_numerosComplejos = new javax.swing.JLabel();
        btn_coor = new javax.swing.JButton();
        lbl_fecha = new javax.swing.JLabel();
        btn_numerosComplejos = new javax.swing.JButton();
        lbl_coor = new javax.swing.JLabel();
        btn_fecha1 = new javax.swing.JButton();
        lbl_fraccion = new javax.swing.JLabel();
        btn_coor1 = new javax.swing.JButton();
        btn_ingresaFraccion = new javax.swing.JButton();
        btn_ingresarFiguras = new javax.swing.JButton();
        btn_ingresarCuenta = new javax.swing.JButton();
        btn_ingresarNumerosComplejos = new javax.swing.JButton();
        btn_ingresarfecha = new javax.swing.JButton();
        btn_ingresarCoordenadas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_cuenta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea_Principal = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_desapilar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel1.setText("Clases");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Figuras_Geometrica.setText("Figuras Geometricas");
        btn_Figuras_Geometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Figuras_GeometricaActionPerformed(evt);
            }
        });

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        lbl_figuras.setText("..........");

        btn_cuenta.setText("Cuenta Bancaria");
        btn_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuentaActionPerformed(evt);
            }
        });

        lbl_numerosComplejos.setText("........");

        btn_coor.setText("Coordenadas");
        btn_coor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coorActionPerformed(evt);
            }
        });

        lbl_fecha.setText("........");

        btn_numerosComplejos.setText("Numeros Complejos");
        btn_numerosComplejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numerosComplejosActionPerformed(evt);
            }
        });

        lbl_coor.setText(".......");

        btn_fecha1.setText("Fecha");
        btn_fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecha1ActionPerformed(evt);
            }
        });

        lbl_fraccion.setText("......");

        btn_coor1.setText("Fraccion");
        btn_coor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coor1ActionPerformed(evt);
            }
        });

        btn_ingresaFraccion.setText("Agregar Fraccion");
        btn_ingresaFraccion.setToolTipText("");
        btn_ingresaFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresaFraccionActionPerformed(evt);
            }
        });

        btn_ingresarFiguras.setText("Agregar Figuras Geometricas");
        btn_ingresarFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarFigurasActionPerformed(evt);
            }
        });

        btn_ingresarCuenta.setText("Agregar Cuenta Bancaria");
        btn_ingresarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarCuentaActionPerformed(evt);
            }
        });

        btn_ingresarNumerosComplejos.setText("Agregar Numeros Complejos");
        btn_ingresarNumerosComplejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarNumerosComplejosActionPerformed(evt);
            }
        });

        btn_ingresarfecha.setText("Agregar Fecha ");
        btn_ingresarfecha.setToolTipText("");
        btn_ingresarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarfechaActionPerformed(evt);
            }
        });

        btn_ingresarCoordenadas.setText("Agregar Coordenadas");
        btn_ingresarCoordenadas.setToolTipText("");
        btn_ingresarCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarCoordenadasActionPerformed(evt);
            }
        });

        txtarea_cuenta.setEditable(false);
        txtarea_cuenta.setColumns(20);
        txtarea_cuenta.setRows(5);
        jScrollPane1.setViewportView(txtarea_cuenta);

        txtArea_Principal.setEditable(false);
        txtArea_Principal.setColumns(20);
        txtArea_Principal.setRows(5);
        jScrollPane3.setViewportView(txtArea_Principal);

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel2.setText("Clases");

        btn_desapilar.setText("Desapilar");
        btn_desapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desapilarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_ingresarNumerosComplejos)
                                    .addComponent(btn_ingresarfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_ingresaFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_numerosComplejos)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_fecha)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(lbl_fraccion))
                                        .addComponent(lbl_coor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_ingresarCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_ingresarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_ingresarFiguras)
                                        .addGap(64, 64, 64)
                                        .addComponent(lbl_figuras)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Insertar)
                                .addGap(49, 49, 49)
                                .addComponent(btn_desapilar)
                                .addGap(113, 113, 113))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Figuras_Geometrica)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cuenta)
                                .addGap(18, 18, 18)
                                .addComponent(btn_numerosComplejos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_fecha1)
                                .addGap(49, 49, 49)
                                .addComponent(btn_coor)
                                .addGap(18, 18, 18)
                                .addComponent(btn_coor1)
                                .addGap(77, 77, 77)))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Figuras_Geometrica)
                    .addComponent(btn_cuenta)
                    .addComponent(btn_numerosComplejos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_coor)
                            .addComponent(btn_coor1)
                            .addComponent(btn_fecha1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresarFiguras)
                            .addComponent(lbl_figuras))
                        .addGap(18, 18, 18)
                        .addComponent(btn_ingresarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresarNumerosComplejos)
                            .addComponent(lbl_numerosComplejos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresarfecha)
                            .addComponent(lbl_fecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresarCoordenadas)
                            .addComponent(lbl_coor))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresaFraccion)
                            .addComponent(lbl_fraccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insertar)
                            .addComponent(btn_desapilar))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Figuras_GeometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Figuras_GeometricaActionPerformed
        // TODO add your handling code here:
        ventana_Figuras_Geometrica = new Ventana_Figuras_Geometrica();
        this.setVisible(false);
        ventana_Figuras_Geometrica.setVisible(true);

    }//GEN-LAST:event_btn_Figuras_GeometricaActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        // TODO add your handling code here:

        try {
            ObjectInputStream lector_figuras = new ObjectInputStream(new FileInputStream(ruta_figura));
            pila_figuras = (Pila) (lector_figuras.readObject());
            lector_figuras.close();

            lbl_figuras.setText(pila_figuras.Peek().toString());

            //-----------------
            ObjectInputStream lector_cuenta = new ObjectInputStream(new FileInputStream(ruta_cuenta));
            pila_cuenta = (Pila) (lector_cuenta.readObject());
            lector_cuenta.close();

            txtarea_cuenta.setText(pila_cuenta.Peek().toString());

            //-----------------
            ObjectInputStream lector_coordenadas = new ObjectInputStream(new FileInputStream(ruta_Coordenadas));
            pila_Coordenadas = (Pila) (lector_coordenadas.readObject());
            lector_coordenadas.close();

            lbl_coor.setText(pila_Coordenadas.Peek().toString());
            //-----------------
            ObjectInputStream lector_fecha = new ObjectInputStream(new FileInputStream(ruta_fecha));
            pila_fecha = (Pila) (lector_fecha.readObject());
            lector_fecha.close();

            lbl_fecha.setText(pila_fecha.Peek().toString());
            //-----------------
            ObjectInputStream lector_numerosComplejos = new ObjectInputStream(new FileInputStream(ruta_numerosComplejos));
            pila_numerosComplejos = (Pila) (lector_numerosComplejos.readObject());
            lector_numerosComplejos.close();
            lbl_numerosComplejos.setText(pila_numerosComplejos.Peek().toString());
            //-----------------
            ObjectInputStream lector_fraccionario = new ObjectInputStream(new FileInputStream(ruta_Fraccion));
            pila_fraccionario = (Pila) (lector_fraccionario.readObject());
            lector_fraccionario.close();
            lbl_fraccion.setText(pila_fraccionario.Peek().toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_InsertarActionPerformed

    private void btn_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuentaActionPerformed
        // TODO add your handling code here:
        ventana_Cuenta_Bancaria = new Ventana_Cuenta_Bancaria();
        ventana_Cuenta_Bancaria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cuentaActionPerformed

    private void btn_coorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coorActionPerformed
        // TODO add your handling code here:
        ventana_Coordenadas = new Ventana_Coordenadas();
        ventana_Coordenadas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_coorActionPerformed

    private void btn_numerosComplejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numerosComplejosActionPerformed
        // TODO add your handling code here:
        ventana_Numeros_Complejos = new Ventana_Numeros_Complejos();
        ventana_Numeros_Complejos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_numerosComplejosActionPerformed

    private void btn_fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecha1ActionPerformed
        // TODO add your handling code here:
        ventana_Fecha = new Ventana_Fecha();
        ventana_Fecha.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_fecha1ActionPerformed

    private void btn_coor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coor1ActionPerformed
        // TODO add your handling code here:
        ventana_Fraccionario = new Ventana_Fraccionario();
        ventana_Fraccionario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_coor1ActionPerformed

    private void btn_ingresarFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarFigurasActionPerformed
        // TODO add your handling code here:

        if (pila_figuras == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_figuras.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_figuras.Peek();
                pila_figuras.Desapilar();
                if (pila_figuras.Vacia()) {
                    lbl_figuras.setText(".........");
                } else {
                    lbl_figuras.setText(pila_figuras.Peek().toString());
                }

                //txtArea_Principal.append("\n" + aux.toString() + "\n");

                pila_principal.apilar(aux);
                txtArea_Principal.setText(pila_principal.toString());
            }
        }


    }//GEN-LAST:event_btn_ingresarFigurasActionPerformed

    private void btn_ingresarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarCuentaActionPerformed
        // TODO add your handling code here:
        if (pila_cuenta == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_cuenta.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_cuenta.Peek();
                pila_cuenta.Desapilar();
                if (pila_cuenta.Vacia()) {
                    txtarea_cuenta.setText(" ");
                } else {
                    txtarea_cuenta.setText(pila_cuenta.Peek().toString());
                }

               // txtArea_Principal.append("\n" + aux.toString() + "\n");

                pila_principal.apilar(aux);
                txtArea_Principal.setText(pila_principal.toString());
            }
        }
    }//GEN-LAST:event_btn_ingresarCuentaActionPerformed

    private void btn_ingresarNumerosComplejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarNumerosComplejosActionPerformed
        // TODO add your handling code here:
        if (pila_numerosComplejos == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_numerosComplejos.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_numerosComplejos.Peek();
                pila_numerosComplejos.Desapilar();
                if (pila_numerosComplejos.Vacia()) {
                    lbl_numerosComplejos.setText(".........");
                } else {
                    lbl_numerosComplejos.setText(((NumerosComplejos) (pila_numerosComplejos.Peek())).toString());
                }

               // txtArea_Principal.append("\n" + ((NumerosComplejos) aux).toString() + "\n");

                pila_principal.apilar(aux);
                txtArea_Principal.setText(pila_principal.toString());
            }
        }
    }//GEN-LAST:event_btn_ingresarNumerosComplejosActionPerformed

    private void btn_ingresarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarfechaActionPerformed
        // TODO add your handling code here:
        if (pila_fecha == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_fecha.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_fecha.Peek();
                pila_fecha.Desapilar();
                if (pila_fecha.Vacia()) {
                    lbl_fecha.setText(".........");
                } else {
                    lbl_fecha.setText(pila_fecha.Peek().toString());
                }

                //txtArea_Principal.append("\n" + aux.toString() + "\n");

                pila_principal.apilar(aux);
                txtArea_Principal.setText(pila_principal.toString());
            }
        }
    }//GEN-LAST:event_btn_ingresarfechaActionPerformed

    private void btn_ingresarCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarCoordenadasActionPerformed
        // TODO add your handling code here:
        if (pila_Coordenadas == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_Coordenadas.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_Coordenadas.Peek();
                pila_Coordenadas.Desapilar();
                if (pila_Coordenadas.Vacia()) {
                    lbl_coor.setText(".........");
                } else {
                    lbl_coor.setText(pila_Coordenadas.Peek().toString());
                }

               // txtArea_Principal.append("\n" + aux.toString() + "\n");

                pila_principal.apilar(aux);
                txtArea_Principal.setText(pila_principal.toString());
            }
        }
    }//GEN-LAST:event_btn_ingresarCoordenadasActionPerformed

    private void btn_ingresaFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresaFraccionActionPerformed
        // TODO add your handling code here:
        if (pila_fraccionario == null) {
            JOptionPane.showMessageDialog(null, "Pila no creada");
        } else {
            if (pila_fraccionario.Vacia()) {
                JOptionPane.showMessageDialog(null, "Pila  vacia");
            } else {
                Object aux = pila_fraccionario.Peek();
                pila_fraccionario.Desapilar();
                if (pila_fraccionario.Vacia()) {
                    lbl_fraccion.setText(".........");
                } else {
                    lbl_fraccion.setText(pila_fraccionario.Peek().toString());
                }

               // txtArea_Principal.append("\n" + aux.toString() + "\n");

                pila_principal.apilar(aux);
                 txtArea_Principal.setText(pila_principal.toString());
            }
        }
    }//GEN-LAST:event_btn_ingresaFraccionActionPerformed

    private void btn_desapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desapilarActionPerformed
        // TODO add your handling code here:

        if (pila_principal.Vacia()) {
             JOptionPane.showMessageDialog(null, "Pila  vacia");
        }
        else{Object cima = pila_principal.Peek();
        pila_principal.Desapilar();

        if (cima instanceof Figura_geometrica) {
            pila_figuras.apilar(cima);
            lbl_figuras.setText(pila_figuras.Peek().toString());
            txtArea_Principal.setText(pila_principal.toString());
        } else {
            if (cima instanceof Coordenadas_polares || cima instanceof Coordenadas_rectangulares) {
                pila_Coordenadas.apilar(cima);
                lbl_coor.setText(pila_Coordenadas.Peek().toString());
                txtArea_Principal.setText(pila_principal.toString());
            } else {
                if (cima instanceof Cuenta) {
                    pila_cuenta.apilar(cima);
                    txtarea_cuenta.setText(pila_cuenta.Peek().toString());
                    txtArea_Principal.setText(pila_principal.toString());
                } else {
                    if (cima instanceof Fecha) {
                        pila_fecha.apilar(cima);
                        lbl_fecha.setText(pila_fecha.Peek().toString());
                        txtArea_Principal.setText(pila_principal.toString());
                    } else {
                        if (cima instanceof Fraccionario) {
                            pila_fraccionario.apilar(cima);
                            lbl_fraccion.setText(pila_fraccionario.Peek().toString());
                            txtArea_Principal.setText(pila_principal.toString());
                        } else {

                            pila_numerosComplejos.apilar(cima);
                            lbl_numerosComplejos.setText(pila_numerosComplejos.Peek().toString());
                            txtArea_Principal.setText(pila_principal.toString());
                        }
                    }
                }
            }
        }}
        
        

    }//GEN-LAST:event_btn_desapilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar;
    private javax.swing.JButton btn_Figuras_Geometrica;
    private javax.swing.JButton btn_coor;
    private javax.swing.JButton btn_coor1;
    private javax.swing.JButton btn_cuenta;
    private javax.swing.JButton btn_desapilar;
    private javax.swing.JButton btn_fecha1;
    private javax.swing.JButton btn_ingresaFraccion;
    private javax.swing.JButton btn_ingresarCoordenadas;
    private javax.swing.JButton btn_ingresarCuenta;
    private javax.swing.JButton btn_ingresarFiguras;
    private javax.swing.JButton btn_ingresarNumerosComplejos;
    private javax.swing.JButton btn_ingresarfecha;
    private javax.swing.JButton btn_numerosComplejos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_coor;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_figuras;
    private javax.swing.JLabel lbl_fraccion;
    private javax.swing.JLabel lbl_numerosComplejos;
    private javax.swing.JTextArea txtArea_Principal;
    private javax.swing.JTextArea txtarea_cuenta;
    // End of variables declaration//GEN-END:variables
}
