package poo.quicksort;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Ordenar arreglo;

    public Ventana() {

        initComponents();        
        this.MostrarLlenarLista(false);
        this.lb_arregloCompleto.setVisible(false);
        this.lb_arregloCreado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_tamañoArreglo = new javax.swing.JPanel();
        lb_tamañoArreglo = new javax.swing.JLabel();
        txt_tamañoArreglo = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        lb_arregloCreado = new javax.swing.JLabel();
        pn_llenarArreglo = new javax.swing.JPanel();
        cb_opcionesLlenarArreglo = new javax.swing.JComboBox<>();
        lb_llenarArreglo = new javax.swing.JLabel();
        txt_llenarArreglo = new javax.swing.JTextField();
        btn_añadir = new javax.swing.JButton();
        pn_mostrarArreglo1 = new javax.swing.JPanel();
        btn_mostrarArreglo1 = new javax.swing.JButton();
        lb_arregloCompleto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pn_ordenar = new javax.swing.JPanel();
        lb_ordenarQuickSort = new javax.swing.JLabel();
        lb_ordenarBurbuja = new javax.swing.JLabel();
        btn_ordenarQuickSort = new javax.swing.JButton();
        btn_ordenarBurbuja = new javax.swing.JButton();
        lb_segundosQuicksort = new javax.swing.JLabel();
        lb_segundosBurbuja = new javax.swing.JLabel();
        txt_segundosQuickSort = new javax.swing.JTextField();
        txt_segundosBurbujas = new javax.swing.JTextField();
        lb_milisegundos1 = new javax.swing.JLabel();
        lb_milisegundos2 = new javax.swing.JLabel();
        txt_milisegundos1 = new javax.swing.JTextField();
        txt_milisegundos2 = new javax.swing.JTextField();
        pn_mostrarArreglo2 = new javax.swing.JPanel();
        btn_mostrarArreglo2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lb_tamañoArreglo.setText("Introducir tamaño del arreglo");

        txt_tamañoArreglo.setText("0");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        lb_arregloCreado.setText("Arreglo creado");

        javax.swing.GroupLayout pn_tamañoArregloLayout = new javax.swing.GroupLayout(pn_tamañoArreglo);
        pn_tamañoArreglo.setLayout(pn_tamañoArregloLayout);
        pn_tamañoArregloLayout.setHorizontalGroup(
            pn_tamañoArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tamañoArregloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_tamañoArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_arregloCreado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_tamañoArregloLayout.createSequentialGroup()
                        .addComponent(lb_tamañoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tamañoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_tamañoArregloLayout.setVerticalGroup(
            pn_tamañoArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tamañoArregloLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_tamañoArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tamañoArreglo)
                    .addComponent(txt_tamañoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_arregloCreado))
        );

        cb_opcionesLlenarArreglo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llenar con números random", "Llenar manualmente" }));
        cb_opcionesLlenarArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opcionesLlenarArregloActionPerformed(evt);
            }
        });

        lb_llenarArreglo.setText("lista,  posicion[ ] =");

        txt_llenarArreglo.setText("0");

        btn_añadir.setText("Añadir");
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_llenarArregloLayout = new javax.swing.GroupLayout(pn_llenarArreglo);
        pn_llenarArreglo.setLayout(pn_llenarArregloLayout);
        pn_llenarArregloLayout.setHorizontalGroup(
            pn_llenarArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_llenarArregloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_opcionesLlenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lb_llenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_llenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pn_llenarArregloLayout.setVerticalGroup(
            pn_llenarArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_llenarArregloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pn_llenarArregloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_opcionesLlenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_llenarArreglo)
                    .addComponent(txt_llenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_añadir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_mostrarArreglo1.setText("Mostrar arreglo");
        btn_mostrarArreglo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarArreglo1ActionPerformed(evt);
            }
        });

        lb_arregloCompleto.setText("Arreglo completo");

        jTextField1.setText("No pude hacer que el arreglo se viera por aqui :''v");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mostrarArreglo1Layout = new javax.swing.GroupLayout(pn_mostrarArreglo1);
        pn_mostrarArreglo1.setLayout(pn_mostrarArreglo1Layout);
        pn_mostrarArreglo1Layout.setHorizontalGroup(
            pn_mostrarArreglo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mostrarArreglo1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pn_mostrarArreglo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_mostrarArreglo1Layout.createSequentialGroup()
                        .addComponent(btn_mostrarArreglo1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_mostrarArreglo1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lb_arregloCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pn_mostrarArreglo1Layout.setVerticalGroup(
            pn_mostrarArreglo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mostrarArreglo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_arregloCompleto)
                .addGroup(pn_mostrarArreglo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_mostrarArreglo1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btn_mostrarArreglo1)
                        .addGap(50, 50, 50))
                    .addGroup(pn_mostrarArreglo1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTextField1)
                        .addContainerGap())))
        );

        lb_ordenarQuickSort.setText("Ordenar por QuickSort");

        lb_ordenarBurbuja.setText("Ordenar por Burbuja");

        btn_ordenarQuickSort.setText("ordenar");
        btn_ordenarQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarQuickSortActionPerformed(evt);
            }
        });

        btn_ordenarBurbuja.setText("ordenar");
        btn_ordenarBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarBurbujaActionPerformed(evt);
            }
        });

        lb_segundosQuicksort.setText("segundos");

        lb_segundosBurbuja.setText("segundos");

        txt_segundosQuickSort.setEditable(false);
        txt_segundosQuickSort.setText("0");
        txt_segundosQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_segundosQuickSortActionPerformed(evt);
            }
        });

        txt_segundosBurbujas.setEditable(false);
        txt_segundosBurbujas.setText("0");

        lb_milisegundos1.setText("milisegundos");

        lb_milisegundos2.setText("milisegundos");

        txt_milisegundos1.setText("0");

        txt_milisegundos2.setText("0");

        javax.swing.GroupLayout pn_ordenarLayout = new javax.swing.GroupLayout(pn_ordenar);
        pn_ordenar.setLayout(pn_ordenarLayout);
        pn_ordenarLayout.setHorizontalGroup(
            pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ordenarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_ordenarQuickSort, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lb_ordenarBurbuja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ordenarQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ordenarBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_segundosQuicksort)
                    .addComponent(lb_segundosBurbuja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ordenarLayout.createSequentialGroup()
                        .addComponent(txt_segundosQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_milisegundos1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_milisegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_ordenarLayout.createSequentialGroup()
                        .addComponent(txt_segundosBurbujas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_milisegundos2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_milisegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_ordenarLayout.setVerticalGroup(
            pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ordenarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ordenarQuickSort)
                    .addComponent(btn_ordenarQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lb_segundosQuicksort)
                    .addComponent(txt_segundosQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_milisegundos1)
                    .addComponent(txt_milisegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pn_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ordenarBurbuja)
                    .addComponent(btn_ordenarBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lb_segundosBurbuja)
                    .addComponent(txt_segundosBurbujas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_milisegundos2)
                    .addComponent(txt_milisegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btn_mostrarArreglo2.setText("Mostrar arreglo");
        btn_mostrarArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarArreglo2ActionPerformed(evt);
            }
        });

        jTextField2.setText("Tampoco pude hacer que el arreglo se viera por aca :'')");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mostrarArreglo2Layout = new javax.swing.GroupLayout(pn_mostrarArreglo2);
        pn_mostrarArreglo2.setLayout(pn_mostrarArreglo2Layout);
        pn_mostrarArreglo2Layout.setHorizontalGroup(
            pn_mostrarArreglo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mostrarArreglo2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_mostrarArreglo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        pn_mostrarArreglo2Layout.setVerticalGroup(
            pn_mostrarArreglo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mostrarArreglo2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pn_mostrarArreglo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrarArreglo2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_tamañoArreglo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_llenarArreglo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_mostrarArreglo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pn_mostrarArreglo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_tamañoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_llenarArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_mostrarArreglo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_mostrarArreglo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:        
        this.indice = 0;
        this.MostrarLlenarLista(false);
        boolean esNumero = this.isNumeric(this.txt_tamañoArreglo.getText());
        this.txt_milisegundos1.setText("0");
        this.txt_milisegundos2.setText("0");
        this.txt_segundosBurbujas.setText("0");
        this.txt_segundosQuickSort.setText("0");

        try {
            if (Integer.parseInt(this.txt_tamañoArreglo.getText()) > 0) {
                if (this.arreglo == null) {
                    this.arreglo = new Ordenar(Integer.parseInt(this.txt_tamañoArreglo.getText()));
                } else {
                    this.arreglo.RedimensioniarLista(Integer.parseInt(this.txt_tamañoArreglo.getText()));
                }
                this.lb_arregloCreado.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Escriba un número positivo y mayor a 0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escriba un número");
        }
        this.lb_arregloCompleto.setVisible(false);
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void cb_opcionesLlenarArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opcionesLlenarArregloActionPerformed
        // TODO add your handling code here:

        if (this.arreglo == null) {
            JOptionPane.showMessageDialog(null, "Crea la lista de numeros");
        } else {
            this.num_opcion = this.cb_opcionesLlenarArreglo.getSelectedIndex();
            if (this.num_opcion == 0) {
                this.arreglo.LlenarLista(this.arreglo.lista);
                this.lb_arregloCompleto.setVisible(true);
                this.MostrarLlenarLista(false);
                this.arreglo.Imprimir2(this.arreglo.lista);
                this.arreglo.Imprimir2(this.arreglo.listaAux);

            } else {
                this.lb_arregloCompleto.setVisible(false);
                this.MostrarLlenarLista(true);
                this.llenarArreglo();
            }
        }

        System.out.println("" + num_opcion);
    }//GEN-LAST:event_cb_opcionesLlenarArregloActionPerformed

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
        // TODO add your handling code here:

        boolean esNumero = this.isNumeric(this.txt_llenarArreglo.getText());

        if (esNumero == true) {
            if (this.indice < this.arreglo.lista.length) {
                this.llenarArreglo();
            } else {
                this.MostrarLlenarLista(false);
                this.lb_arregloCompleto.setVisible(true);
                this.arreglo.LlenarListaAux(this.arreglo.lista, this.arreglo.listaAux);
                this.arreglo.Imprimir2(this.arreglo.lista);
                this.arreglo.Imprimir2(this.arreglo.listaAux);
            }
        } else {
            this.txt_llenarArreglo.setText("0");
            JOptionPane.showMessageDialog(null, "Escriba un número");
        }
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_ordenarQuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarQuickSortActionPerformed
        // TODO add your handling code here:
        if (this.arreglo == null) {
            JOptionPane.showMessageDialog(null, "Revisa el arreglo");
        } else {
            long inicio = System.currentTimeMillis();
            this.arreglo.QuickSort(this.arreglo.lista, 0, this.arreglo.lista.length - 1);
            long fin = System.currentTimeMillis();
            double tiempo = (double) ((fin - inicio) / 1000);
            this.txt_segundosQuickSort.setText(tiempo + "");
            this.arreglo.Imprimir2(this.arreglo.lista);
            this.txt_milisegundos1.setText((fin - inicio) + "");
        }
    }//GEN-LAST:event_btn_ordenarQuickSortActionPerformed

    private void btn_ordenarBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarBurbujaActionPerformed
        // TODO add your handling code here:
        if (this.arreglo == null) {
            JOptionPane.showMessageDialog(null, "Revisa el arreglo");
        } else {
            long inicio = System.currentTimeMillis();
            this.arreglo.OrdenarBurbuja(this.arreglo.listaAux);
            long fin = System.currentTimeMillis();
            double tiempo = (double) ((fin - inicio) / 1000);
            this.txt_segundosBurbujas.setText(tiempo + "");
            this.arreglo.Imprimir2(this.arreglo.listaAux);
            this.txt_milisegundos2.setText((fin - inicio) + "");
        }
    }//GEN-LAST:event_btn_ordenarBurbujaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btn_mostrarArreglo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarArreglo1ActionPerformed
        if (this.arreglo == null) {
            JOptionPane.showMessageDialog(null, "Revisa el arreglo");

        } else {

        }
    }//GEN-LAST:event_btn_mostrarArreglo1ActionPerformed

    private void btn_mostrarArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarArreglo2ActionPerformed
        if (this.arreglo == null) {
            JOptionPane.showMessageDialog(null, "Revisa el arreglo");

        } else {

        }
    }//GEN-LAST:event_btn_mostrarArreglo2ActionPerformed

    private void txt_segundosQuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_segundosQuickSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_segundosQuickSortActionPerformed

    public void llenarArreglo() {
        if (this.indice < this.arreglo.lista.length) {
            this.lb_llenarArreglo.setText("lista, posición [" + (indice + 1) + "]:");
            this.arreglo.CambiarValores(this.indice, Integer.parseInt(this.txt_llenarArreglo.getText()));
            this.txt_llenarArreglo.setText("0");
            this.indice++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    public void MostrarLlenarLista(boolean mostrar) {
        this.lb_llenarArreglo.setVisible(mostrar);
        this.txt_llenarArreglo.setVisible(mostrar);
        this.btn_añadir.setVisible(mostrar);
    }

    int indice;
    int num_opcion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_mostrarArreglo1;
    private javax.swing.JButton btn_mostrarArreglo2;
    private javax.swing.JButton btn_ordenarBurbuja;
    private javax.swing.JButton btn_ordenarQuickSort;
    private javax.swing.JComboBox<String> cb_opcionesLlenarArreglo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_arregloCompleto;
    private javax.swing.JLabel lb_arregloCreado;
    private javax.swing.JLabel lb_llenarArreglo;
    private javax.swing.JLabel lb_milisegundos1;
    private javax.swing.JLabel lb_milisegundos2;
    private javax.swing.JLabel lb_ordenarBurbuja;
    private javax.swing.JLabel lb_ordenarQuickSort;
    private javax.swing.JLabel lb_segundosBurbuja;
    private javax.swing.JLabel lb_segundosQuicksort;
    private javax.swing.JLabel lb_tamañoArreglo;
    private javax.swing.JPanel pn_llenarArreglo;
    private javax.swing.JPanel pn_mostrarArreglo1;
    private javax.swing.JPanel pn_mostrarArreglo2;
    private javax.swing.JPanel pn_ordenar;
    private javax.swing.JPanel pn_tamañoArreglo;
    private javax.swing.JTextField txt_llenarArreglo;
    private javax.swing.JTextField txt_milisegundos1;
    private javax.swing.JTextField txt_milisegundos2;
    private javax.swing.JTextField txt_segundosBurbujas;
    private javax.swing.JTextField txt_segundosQuickSort;
    private javax.swing.JTextField txt_tamañoArreglo;
    // End of variables declaration//GEN-END:variables
}
