/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figurasgeometricasappvisual;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.RestaurarValores();
        this.OcultarAtributos(true);
        this.setLocationByPlatform(true);
        this.mover = 10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloAplicacion = new javax.swing.JLabel();
        CbFigurasGeometricas = new javax.swing.JComboBox<>();
        LbPunto = new javax.swing.JLabel();
        LbAtributo1 = new javax.swing.JLabel();
        LbAtributo2 = new javax.swing.JLabel();
        LbAtributo3 = new javax.swing.JLabel();
        LbX1 = new javax.swing.JLabel();
        LbX2 = new javax.swing.JLabel();
        LbY3 = new javax.swing.JLabel();
        LbX3 = new javax.swing.JLabel();
        LbY1 = new javax.swing.JLabel();
        LbY2 = new javax.swing.JLabel();
        TxtX2 = new javax.swing.JTextField();
        TxtX3 = new javax.swing.JTextField();
        TxtX1 = new javax.swing.JTextField();
        TxtY1 = new javax.swing.JTextField();
        TxtY3 = new javax.swing.JTextField();
        TxtY2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LbArea = new javax.swing.JLabel();
        LbPerimetro = new javax.swing.JLabel();
        LbPosicion = new javax.swing.JLabel();
        BtnPosicion = new javax.swing.JButton();
        BtnCalcularPerimetro = new javax.swing.JButton();
        BtnCalcularArea = new javax.swing.JButton();
        TxtArea = new javax.swing.JTextField();
        TxtPerimetro = new javax.swing.JTextField();
        TxtPosicion = new javax.swing.JTextField();
        CbCambiarPosicion = new javax.swing.JComboBox<>();
        LbDx = new javax.swing.JLabel();
        LbDy = new javax.swing.JLabel();
        TxtDy = new javax.swing.JTextField();
        txtDx = new javax.swing.JTextField();
        BtnCambiarPosicion = new javax.swing.JButton();
        LbNuevaPosicion = new javax.swing.JLabel();
        txtNuevaPosicion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloAplicacion.setFont(new java.awt.Font("Dosis", 1, 18)); // NOI18N
        lbTituloAplicacion.setText("FIGURAS GEOMÉTRICAS");

        CbFigurasGeometricas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recta", "Triangulo", "Cuadrado", "Rectángulo", "Circunferencia", "Elipse" }));
        CbFigurasGeometricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbFigurasGeometricasActionPerformed(evt);
            }
        });

        LbPunto.setText("Características");

        LbAtributo1.setText("Atributo1");

        LbAtributo2.setText("Atributo2");

        LbAtributo3.setText("Atributo3");

        LbX1.setText("x:");

        LbX2.setText("x:");

        LbY3.setText("y");

        LbX3.setText("x:");

        LbY1.setText("y");

        LbY2.setText("y");

        TxtX2.setMinimumSize(new java.awt.Dimension(16, 24));

        TxtX3.setMinimumSize(new java.awt.Dimension(16, 24));
        TxtX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtX3ActionPerformed(evt);
            }
        });

        TxtX1.setMinimumSize(new java.awt.Dimension(16, 24));

        TxtY1.setMinimumSize(new java.awt.Dimension(16, 24));

        TxtY3.setMinimumSize(new java.awt.Dimension(16, 24));

        TxtY2.setMinimumSize(new java.awt.Dimension(16, 24));

        jLabel1.setText("Seleccionar Figura    ");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LbArea.setText("Area");

        LbPerimetro.setText("Perimetro");

        LbPosicion.setText("Posición");

        BtnPosicion.setText("mostrar");
        BtnPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPosicionActionPerformed(evt);
            }
        });

        BtnCalcularPerimetro.setText("calcular");
        BtnCalcularPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularPerimetroActionPerformed(evt);
            }
        });

        BtnCalcularArea.setText("calcular");
        BtnCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularAreaActionPerformed(evt);
            }
        });

        CbCambiarPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desplazar", "Nueva Posicion" }));
        CbCambiarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCambiarPosicionActionPerformed(evt);
            }
        });

        LbDx.setText("x");

        LbDy.setText("y");

        BtnCambiarPosicion.setText("cambiar posición");
        BtnCambiarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarPosicionActionPerformed(evt);
            }
        });

        LbNuevaPosicion.setText("Nueva Posición");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lbTituloAplicacion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbNuevaPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNuevaPosicion))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LbX2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(LbAtributo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LbAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LbPunto))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LbX1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LbX3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BtnPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BtnCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BtnCalcularPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(LbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LbPosicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LbPerimetro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(CbCambiarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDx, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(LbDy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(BtnCambiarPosicion))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtX3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbY3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtY3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbY2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbY1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(CbFigurasGeometricas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(TxtPerimetro)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TxtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloAplicacion)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LbPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbAtributo1)
                            .addComponent(LbX1)
                            .addComponent(LbY1)
                            .addComponent(TxtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbAtributo2)
                            .addComponent(LbX2)
                            .addComponent(LbY2)
                            .addComponent(TxtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbAtributo3)
                            .addComponent(LbX3)
                            .addComponent(LbY3)
                            .addComponent(TxtX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(CbFigurasGeometricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbArea)
                    .addComponent(BtnCalcularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbPerimetro)
                            .addComponent(BtnCalcularPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbPosicion)
                            .addComponent(BtnPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbCambiarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDx)
                    .addComponent(LbDy)
                    .addComponent(TxtDy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCambiarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNuevaPosicion)
                    .addComponent(txtNuevaPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbFigurasGeometricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbFigurasGeometricasActionPerformed
        this.opcion = this.CbFigurasGeometricas.getSelectedIndex();
        if (opcion == 0) {
            this.acederMetodos = 1;
            this.OcultarAtributos(true);
            this.RestaurarValores();
            this.AtributosRecta();
        } else {
            if (this.opcion == 1) {
                this.acederMetodos = 1;
                this.OcultarAtributos(true);
                this.RestaurarValores();
                this.AtributosTriangulo();
            } else {
                if (this.opcion == 2) {
                    this.acederMetodos = 1;
                    this.OcultarAtributos(true);
                    this.RestaurarValores();
                    this.AtributosCuadrado();
                } else {
                    if (this.opcion == 3) {
                        this.acederMetodos = 1;
                        this.OcultarAtributos(true);
                        this.RestaurarValores();
                        this.AtributosRectangulo();
                    } else {
                        if (this.opcion == 4) {
                            this.acederMetodos = 1;
                            this.OcultarAtributos(true);
                            this.RestaurarValores();
                            this.AtributosCircunferencia();
                        } else {
                            this.acederMetodos = 1;
                            this.OcultarAtributos(true);
                            this.RestaurarValores();
                            this.AtributosElipse();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_CbFigurasGeometricasActionPerformed

    private void TxtX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtX3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.acederMetodos == 1) {
            this.MostrarOperaciones();
        }
        if (this.opcion == 0) {
            if (this.recta == null) {
                this.recta = new Recta(Integer.parseInt(this.TxtX2.getText()), Integer.parseInt(this.TxtY2.getText()), Integer.parseInt(this.TxtX3.getText()), Integer.parseInt(this.TxtY3.getText()));
            } else {
                this.recta.puntoInicio.setX(Integer.parseInt(this.TxtX2.getText()));
                this.recta.puntoInicio.setY(Integer.parseInt(this.TxtY2.getText()));
                this.recta.puntoFinal.setX(Integer.parseInt(this.TxtX3.getText()));
                this.recta.puntoFinal.setY(Integer.parseInt(this.TxtY3.getText()));
            }
        } else {
            if (this.opcion == 1) {
                if (this.triangulo == null) {
                    this.triangulo = new Triangulo(Integer.parseInt(this.TxtX1.getText()), Integer.parseInt(this.TxtY1.getText()), Integer.parseInt(this.TxtX2.getText()), Integer.parseInt(this.TxtY2.getText()), Integer.parseInt(this.TxtX3.getText()), Integer.parseInt(this.TxtY3.getText()));
                } else {
                    this.triangulo.verticeA.setX(Integer.parseInt(this.TxtX1.getText()));
                    this.triangulo.verticeA.setY(Integer.parseInt(this.TxtY1.getText()));
                    this.triangulo.verticeB.setX(Integer.parseInt(this.TxtX2.getText()));
                    this.triangulo.verticeB.setY(Integer.parseInt(this.TxtY2.getText()));
                    this.triangulo.verticeC.setX(Integer.parseInt(this.TxtX3.getText()));
                    this.triangulo.verticeC.setY(Integer.parseInt(this.TxtY3.getText()));
                }
            } else {
                if (this.opcion == 2) {
                    if (this.cuadrado == null) {
                        this.cuadrado = new Cuadrado(Integer.parseInt(this.TxtX3.getText()), Integer.parseInt(this.TxtX2.getText()), Integer.parseInt(this.TxtY2.getText()));
                    } else {
                        this.cuadrado.puntoOrigen.setX(Integer.parseInt(this.TxtX2.getText()));
                        this.cuadrado.puntoOrigen.setY(Integer.parseInt(this.TxtY2.getText()));
                        this.cuadrado.setLado(Integer.parseInt(this.TxtX3.getText()));
                    }
                } else {
                    if (opcion == 3) {
                        if (this.rectangulo == null) {
                            this.rectangulo = new Rectangulo(Integer.parseInt(this.TxtX1.getText()), Integer.parseInt(this.TxtY1.getText()), Double.parseDouble(this.TxtX2.getText()), Double.parseDouble(this.TxtX3.getText()));
                        } else {
                            this.rectangulo.puntoOrigen.setX(Integer.parseInt(this.TxtX1.getText()));
                            this.rectangulo.puntoOrigen.setY(Integer.parseInt(this.TxtY1.getText()));
                            this.rectangulo.setLado1(Double.parseDouble(this.TxtX2.getText()));
                        }
                        this.rectangulo.setLado2(Double.parseDouble(this.TxtX3.getText()));
                    } else {
                        if (opcion == 4) {
                            if (this.circunferencia == null) {
                                this.circunferencia = new Circunferencia(Double.parseDouble(this.TxtX3.getText()), Integer.parseInt(this.TxtX2.getText()), Integer.parseInt(this.TxtY2.getText()));
                            } else {
                                this.circunferencia.centro.setX(Integer.parseInt(this.TxtX2.getText()));
                                this.circunferencia.centro.setY(Integer.parseInt(this.TxtX2.getText()));
                                this.circunferencia.setRadio(Double.parseDouble(this.TxtX3.getText()));
                            }
                        } else {
                            if (this.elipse == null) {
                                this.elipse = new Elipse(Integer.parseInt(this.TxtX1.getText()), Integer.parseInt(this.TxtY1.getText()), Double.parseDouble(this.TxtX2.getText()), Double.parseDouble(this.TxtX3.getText()));
                            } else {
                                this.elipse.centro.setX(Integer.parseInt(this.TxtX1.getText()));
                                this.elipse.centro.setY(Integer.parseInt(this.TxtY1.getText()));
                                this.elipse.setEjeMayor(Double.parseDouble(this.TxtX2.getText()));
                                this.elipse.setEjeMenor(Double.parseDouble(this.TxtX3.getText()));
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularAreaActionPerformed
        if (this.opcion == 0) {
            this.TxtArea.setText("no tiene área");
        } else {
            if (this.opcion == 1) {
                this.TxtArea.setText(this.triangulo.CalcularArea() + "");
            } else {
                if (this.opcion == 2) {
                    this.TxtArea.setText(this.cuadrado.CalcularArea() + "");
                } else {
                    if (this.opcion == 3) {
                        this.TxtArea.setText(this.rectangulo.CalcularArea() + "");
                    } else {
                        if (this.opcion == 4) {
                            this.TxtArea.setText(this.circunferencia.CalcularArea() + "");
                        } else {
                            this.TxtArea.setText(this.elipse.CalcularArea() + "");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BtnCalcularAreaActionPerformed

    private void BtnCalcularPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularPerimetroActionPerformed
        if (this.opcion == 0) {
            this.TxtPerimetro.setText(this.recta.Longitud() + "");
        } else {
            if (this.opcion == 1) {
                this.TxtPerimetro.setText(this.triangulo.CalcularPerimetro() + "");
            } else {
                if (this.opcion == 2) {
                    this.TxtPerimetro.setText(this.cuadrado.CalcularPerimetro() + "");
                } else {
                    if (this.opcion == 3) {
                        this.TxtPerimetro.setText(this.rectangulo.CalcularPerimetro() + "");
                    } else {
                        if (this.opcion == 4) {
                            this.TxtPerimetro.setText(this.circunferencia.CalcularPerimetro() + "");
                        } else {
                            this.TxtPerimetro.setText(this.elipse.CalcularPerimetro2() + "");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BtnCalcularPerimetroActionPerformed

    private void BtnPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPosicionActionPerformed
        this.CambiarPosicion();
    }//GEN-LAST:event_BtnPosicionActionPerformed

    private void CbCambiarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCambiarPosicionActionPerformed
        this.txtDx.setText("0");
        this.TxtDy.setText("0");
        this.mover = this.CbCambiarPosicion.getSelectedIndex();
        this.MostrarOperacionMovimiento(rootPaneCheckingEnabled);
    }//GEN-LAST:event_CbCambiarPosicionActionPerformed

    private void BtnCambiarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarPosicionActionPerformed
        this.CambiarPosicion();
        this.txtNuevaPosicion.setVisible(true);
        this.LbNuevaPosicion.setVisible(true);
    }//GEN-LAST:event_BtnCambiarPosicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public void CambiarPosicion() {
        if (this.opcion == 0) {
            if (this.mover == 0) {
                this.recta.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                this.TxtPosicion.setText(this.recta.puntoInicio.Coordenada());
                this.txtNuevaPosicion.setText(this.recta.puntoInicio.Coordenada());
            } else {
                if (this.mover == 1) {
                    this.recta.puntoInicio.setX(Integer.parseInt(this.txtDx.getText()));
                    this.recta.puntoInicio.setY(Integer.parseInt(this.TxtDy.getText()));
                    this.TxtPosicion.setText(this.recta.puntoInicio.Coordenada());
                    this.txtNuevaPosicion.setText(this.recta.puntoInicio.Coordenada());
                } else {
                    this.TxtPosicion.setText(this.recta.puntoInicio.Coordenada());
                }
            }
        } else {
            if (this.opcion == 1) {
                if (this.mover == 0) {
                    this.triangulo.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                    this.TxtPosicion.setText(this.triangulo.verticeA.Coordenada());
                    this.txtNuevaPosicion.setText(this.triangulo.verticeA.Coordenada());
                } else {
                    if (this.mover == 1) {
                        this.triangulo.verticeA.setX(this.triangulo.verticeA.getX() + Integer.parseInt(this.txtDx.getText()));
                        this.triangulo.verticeA.setY(this.triangulo.verticeA.getY() + Integer.parseInt(this.TxtDy.getText()));
                        this.TxtPosicion.setText(this.triangulo.verticeA.Coordenada());
                        this.txtNuevaPosicion.setText(this.triangulo.verticeA.Coordenada());
                    } else {
                        this.TxtPosicion.setText(this.triangulo.verticeA.Coordenada());
                    }
                }
            } else {
                if (this.opcion == 2) {
                    if (this.mover == 0) {
                        this.cuadrado.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                        this.TxtPosicion.setText(this.cuadrado.puntoOrigen.Coordenada());
                        this.txtNuevaPosicion.setText(this.cuadrado.puntoOrigen.Coordenada());
                    } else {
                        if (this.mover == 1) {
                            this.cuadrado.puntoOrigen.setX(Integer.parseInt(this.txtDx.getText()));
                            this.cuadrado.puntoOrigen.setY(Integer.parseInt(this.TxtDy.getText()));
                            this.TxtPosicion.setText(this.cuadrado.puntoOrigen.Coordenada());
                            this.txtNuevaPosicion.setText(this.cuadrado.puntoOrigen.Coordenada());
                        } else {
                            this.TxtPosicion.setText(this.cuadrado.puntoOrigen.Coordenada());
                        }
                    }
                } else {
                    if (this.opcion == 3) {
                        if (this.mover == 0) {
                            this.rectangulo.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                            this.TxtPosicion.setText(this.rectangulo.puntoOrigen.Coordenada());
                            this.txtNuevaPosicion.setText(this.rectangulo.puntoOrigen.Coordenada());
                        } else {
                            if (this.mover == 1) {
                                this.rectangulo.puntoOrigen.setX(this.rectangulo.puntoOrigen.getX() + Integer.parseInt(this.txtDx.getText()));
                                this.rectangulo.puntoOrigen.setY(this.rectangulo.puntoOrigen.getY() + Integer.parseInt(this.TxtDy.getText()));
                                this.TxtPosicion.setText(this.rectangulo.puntoOrigen.Coordenada());
                                this.txtNuevaPosicion.setText(this.rectangulo.puntoOrigen.Coordenada());
                            } else {
                                this.TxtPosicion.setText(this.rectangulo.puntoOrigen.Coordenada());
                            }
                        }
                    } else {
                        if (this.opcion == 4) {
                            if (this.mover == 0) {
                                this.circunferencia.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                                this.TxtPosicion.setText(this.circunferencia.centro.Coordenada());
                                this.txtNuevaPosicion.setText(this.circunferencia.centro.Coordenada());
                            } else {
                                if (this.mover == 1) {
                                    this.circunferencia.centro.setX(Integer.parseInt(this.txtDx.getText()));
                                    this.circunferencia.centro.setY(Integer.parseInt(this.TxtDy.getText()));
                                    this.TxtPosicion.setText(this.circunferencia.centro.Coordenada());
                                    this.txtNuevaPosicion.setText(this.circunferencia.centro.Coordenada());
                                } else {
                                    this.TxtPosicion.setText(this.circunferencia.centro.Coordenada());
                                }
                            }
                        } else {
                            if (this.mover == 0) {
                                this.elipse.Mover(Integer.parseInt(this.txtDx.getText()), Integer.parseInt(this.TxtDy.getText()));
                                this.TxtPosicion.setText(this.elipse.centro.Coordenada());
                                this.txtNuevaPosicion.setText(this.elipse.centro.Coordenada());
                            } else {
                                if (this.mover == 1) {
                                    this.elipse.centro.setX(Integer.parseInt(this.txtDx.getText()));
                                    this.elipse.centro.setY(Integer.parseInt(this.TxtDy.getText()));
                                    this.TxtPosicion.setText(this.elipse.centro.Coordenada());
                                    this.txtNuevaPosicion.setText(this.elipse.centro.Coordenada());
                                } else {
                                    this.TxtPosicion.setText(this.elipse.centro.Coordenada());
                                }
                            }
                        }
                    }
                }
            }
        }
    }


    public void AtributosElipse() {
        this.LbAtributo1.setText("Punto Centro");
        this.LbAtributo2.setText("Eje Mayor");
        this.LbAtributo3.setText("Eje Menor");
        this.LbAtributo1.setVisible(true);
        this.LbAtributo2.setVisible(true);
        this.LbAtributo3.setVisible(true);
        this.LbX1.setVisible(true);
        this.LbY1.setVisible(true);
        this.TxtX1.setVisible(true);
        this.TxtY1.setVisible(true);
        this.TxtX2.setVisible(true);
        this.TxtX3.setVisible(true);
    }

    public void AtributosCircunferencia() {
        this.LbAtributo2.setText("Punto Centro");
        this.LbAtributo3.setText("Radio");
        this.LbAtributo2.setVisible(true);
        this.LbAtributo3.setVisible(true);
        this.TxtX3.setVisible(true);
        this.TxtX2.setVisible(true);
        this.TxtY2.setVisible(true);
        this.LbX2.setVisible(true);
        this.LbY2.setVisible(true);
    }

    public void AtributosRectangulo() {
        this.LbAtributo1.setText("Punto Origen");
        this.LbAtributo2.setText("Tamaño Lado1");
        this.LbAtributo3.setText("Tamaño Lado2");
        this.LbAtributo1.setVisible(true);
        this.LbAtributo2.setVisible(true);
        this.LbAtributo3.setVisible(true);
        this.TxtX2.setVisible(true);
        this.TxtX3.setVisible(true);
        this.TxtX1.setVisible(true);
        this.TxtY1.setVisible(true);
        this.LbX1.setVisible(true);
        this.LbY1.setVisible(true);

    }

    public void AtributosCuadrado() {
        this.LbAtributo2.setText("Punto Origen");
        this.LbAtributo3.setText("Tamaño Lado");
        this.LbAtributo2.setVisible(true);
        this.LbAtributo3.setVisible(true);
        this.LbX2.setVisible(true);
        this.LbY2.setVisible(true);
        this.TxtX3.setVisible(true);
        this.TxtX2.setVisible(true);
        this.TxtY2.setVisible(true);
    }

    public void AtributosTriangulo() {
        this.LbAtributo1.setText("Vertice A");
        this.LbAtributo2.setText("Vertice B");
        this.LbAtributo3.setText("Vertice C");
        this.OcultarAtributos(false);
    }

    public void AtributosRecta() {
        this.LbAtributo2.setText("Punto Inicio");
        this.LbAtributo3.setText("Punto Final");
        this.LbAtributo2.setVisible(true);
        this.LbAtributo3.setVisible(true);
        this.LbX2.setVisible(true);
        this.LbY2.setVisible(true);
        this.LbX3.setVisible(true);
        this.LbY3.setVisible(true);
        this.TxtX2.setVisible(true);
        this.TxtY2.setVisible(true);
        this.TxtX3.setVisible(true);
        this.TxtY3.setVisible(true);
    }

    public void RestaurarValores() {
        this.TxtX1.setText("0");
        this.TxtY1.setText("0");
        this.TxtX2.setText("0");
        this.TxtY2.setText("0");
        this.TxtX3.setText("0");
        this.TxtY3.setText("0");
        this.TxtArea.setText("0");
        this.TxtPerimetro.setText("0");
        this.TxtPosicion.setText("0");
        this.txtDx.setText("0");
        this.TxtDy.setText("0");

    }

    public void MostrarOperacionMovimiento(boolean mostrar) {
        if (mostrar == true) {
            this.LbDx.setVisible(true);
            this.LbDy.setVisible(true);
            this.txtDx.setVisible(true);
            this.TxtDy.setVisible(true);
            this.BtnCambiarPosicion.setVisible(true);
        } else {
            this.LbDx.setVisible(false);
            this.LbDy.setVisible(false);
            this.txtDx.setVisible(false);
            this.TxtDy.setVisible(false);
            this.BtnCambiarPosicion.setVisible(false);
        }
    }

    public void MostrarOperaciones() {
        this.BtnCalcularArea.setVisible(true);
        this.BtnCalcularPerimetro.setVisible(true);
        this.BtnPosicion.setVisible(true);
        this.CbCambiarPosicion.setVisible(true);
        this.TxtArea.setVisible(true);
        this.TxtPosicion.setVisible(true);
        this.TxtPerimetro.setVisible(true);
        this.LbPosicion.setVisible(true);
        this.LbArea.setVisible(true);
        this.LbPerimetro.setVisible(true);
    }

    public void OcultarAtributos(boolean ocultar) {
        if (ocultar == true) {
            this.LbAtributo1.setVisible(false);
            this.LbAtributo2.setVisible(false);
            this.LbAtributo3.setVisible(false);
            this.LbX1.setVisible(false);
            this.LbY1.setVisible(false);
            this.LbX2.setVisible(false);
            this.LbY2.setVisible(false);
            this.LbX3.setVisible(false);
            this.LbY3.setVisible(false);
            this.TxtX1.setVisible(false);
            this.TxtY1.setVisible(false);
            this.TxtX2.setVisible(false);
            this.TxtY2.setVisible(false);
            this.TxtX3.setVisible(false);
            this.TxtY3.setVisible(false);
            this.LbDx.setVisible(false);
            this.LbDy.setVisible(false);
            this.txtDx.setVisible(false);
            this.TxtDy.setVisible(false);
            this.LbArea.setVisible(false);
            this.LbPosicion.setVisible(false);
            this.LbPerimetro.setVisible(false);
            this.BtnCalcularArea.setVisible(false);
            this.BtnCalcularPerimetro.setVisible(false);
            this.BtnPosicion.setVisible(false);
            this.CbCambiarPosicion.setVisible(false);
            this.TxtArea.setVisible(false);
            this.TxtPosicion.setVisible(false);
            this.TxtPerimetro.setVisible(false);
            this.BtnCambiarPosicion.setVisible(false);
            this.txtNuevaPosicion.setVisible(false);
            this.LbNuevaPosicion.setVisible(false);
        } else {
            this.LbAtributo1.setVisible(true);
            this.LbAtributo2.setVisible(true);
            this.LbAtributo3.setVisible(true);
            this.LbX1.setVisible(true);
            this.LbY1.setVisible(true);
            this.LbX2.setVisible(true);
            this.LbY2.setVisible(true);
            this.LbX3.setVisible(true);
            this.LbY3.setVisible(true);
            this.TxtX1.setVisible(true);
            this.TxtY1.setVisible(true);
            this.TxtX2.setVisible(true);
            this.TxtY2.setVisible(true);
            this.TxtX3.setVisible(true);
            this.TxtY3.setVisible(true);
        }
    }

    int opcion, acederMetodos, mover;
    Recta recta;
    Triangulo triangulo;
    Cuadrado cuadrado;
    Rectangulo rectangulo;
    Circunferencia circunferencia;
    Elipse elipse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcularArea;
    private javax.swing.JButton BtnCalcularPerimetro;
    private javax.swing.JButton BtnCambiarPosicion;
    private javax.swing.JButton BtnPosicion;
    private javax.swing.JComboBox<String> CbCambiarPosicion;
    private javax.swing.JComboBox<String> CbFigurasGeometricas;
    private javax.swing.JLabel LbArea;
    private javax.swing.JLabel LbAtributo1;
    private javax.swing.JLabel LbAtributo2;
    private javax.swing.JLabel LbAtributo3;
    private javax.swing.JLabel LbDx;
    private javax.swing.JLabel LbDy;
    private javax.swing.JLabel LbNuevaPosicion;
    private javax.swing.JLabel LbPerimetro;
    private javax.swing.JLabel LbPosicion;
    private javax.swing.JLabel LbPunto;
    private javax.swing.JLabel LbX1;
    private javax.swing.JLabel LbX2;
    private javax.swing.JLabel LbX3;
    private javax.swing.JLabel LbY1;
    private javax.swing.JLabel LbY2;
    private javax.swing.JLabel LbY3;
    private javax.swing.JTextField TxtArea;
    private javax.swing.JTextField TxtDy;
    private javax.swing.JTextField TxtPerimetro;
    private javax.swing.JTextField TxtPosicion;
    private javax.swing.JTextField TxtX1;
    private javax.swing.JTextField TxtX2;
    private javax.swing.JTextField TxtX3;
    private javax.swing.JTextField TxtY1;
    private javax.swing.JTextField TxtY2;
    private javax.swing.JTextField TxtY3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbTituloAplicacion;
    private javax.swing.JTextField txtDx;
    private javax.swing.JTextField txtNuevaPosicion;
    // End of variables declaration//GEN-END:variables
}
