/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appcuentabancaria;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnPresentacion = new javax.swing.JPanel();
        lbTituloAplicacion = new javax.swing.JLabel();
        LbEstudiante = new javax.swing.JLabel();
        LbCurso = new javax.swing.JLabel();
        LbUniversidad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LbCrearCuenta = new javax.swing.JLabel();
        BtnCrearCuenta = new javax.swing.JButton();
        LbRevisarDatos = new javax.swing.JLabel();
        BtnRevisarDatos = new javax.swing.JButton();
        LbTransacciones = new javax.swing.JLabel();
        BtnTransaccion = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTituloAplicacion.setFont(new java.awt.Font("Dosis", 1, 18)); // NOI18N
        lbTituloAplicacion.setText("CUENTA BANCARIA");

        LbEstudiante.setText("Ramírez Henry");

        LbCurso.setText("Programación Orientada a Objetos");

        LbUniversidad.setText("Universidad Técnica del Norte");

        javax.swing.GroupLayout PnPresentacionLayout = new javax.swing.GroupLayout(PnPresentacion);
        PnPresentacion.setLayout(PnPresentacionLayout);
        PnPresentacionLayout.setHorizontalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lbTituloAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(LbUniversidad)
                .addGap(14, 14, 14))
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCurso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnPresentacionLayout.setVerticalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloAplicacion)
                    .addComponent(LbUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbEstudiante)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        LbCrearCuenta.setText("CREAR CUENTA");

        BtnCrearCuenta.setText("Crear");
        BtnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearCuentaActionPerformed(evt);
            }
        });

        LbRevisarDatos.setText("REVISAR DATOS DE LA CUENTA");

        BtnRevisarDatos.setText("Revisar");
        BtnRevisarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRevisarDatosActionPerformed(evt);
            }
        });

        LbTransacciones.setText("REALIZAR TRANSACCIONES");

        BtnTransaccion.setText("Realizar");
        BtnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaccionActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField1.setText("~Por favor cree una cuenta primero~");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LbCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRevisarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbRevisarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbCrearCuenta)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCrearCuenta)
                        .addGap(18, 18, 18)
                        .addComponent(LbRevisarDatos)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRevisarDatos)
                        .addGap(27, 27, 27)
                        .addComponent(LbTransacciones)
                        .addGap(27, 27, 27)
                        .addComponent(BtnTransaccion))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRevisarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRevisarDatosActionPerformed
        if (this.ventanaRevisarDatos == null) {
            this.ventanaRevisarDatos = new VentanaRevisarDatos();
            this.ventanaRevisarDatos.setVisible(true);
            this.setVisible(false);
        } else {
            this.ventanaRevisarDatos.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BtnRevisarDatosActionPerformed

    private void BtnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearCuentaActionPerformed
        if (this.ventanaCrearCuenta == null) {
            this.ventanaCrearCuenta = new VentanaCrearCuenta();
            this.ventanaCrearCuenta.setVisible(true);
            this.dispose();
        } else {
            this.ventanaCrearCuenta.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BtnCrearCuentaActionPerformed

    private void BtnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaccionActionPerformed
        if (this.ventanaTransaccion == null) {
            this.ventanaTransaccion = new VentanaTransaccion();
            this.ventanaTransaccion.setVisible(true);
            this.dispose();
        } else {
            this.ventanaTransaccion.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BtnTransaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    VentanaCrearCuenta ventanaCrearCuenta;
    VentanaRevisarDatos ventanaRevisarDatos;
    VentanaTransaccion ventanaTransaccion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearCuenta;
    private javax.swing.JButton BtnRevisarDatos;
    private javax.swing.JButton BtnTransaccion;
    private javax.swing.JLabel LbCrearCuenta;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbEstudiante;
    private javax.swing.JLabel LbRevisarDatos;
    private javax.swing.JLabel LbTransacciones;
    private javax.swing.JLabel LbUniversidad;
    private javax.swing.JPanel PnPresentacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbTituloAplicacion;
    // End of variables declaration//GEN-END:variables
}
