/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appfracciones;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.OcultarRequisitosOperacionesMixto(false);
        this.OcultarRequisitosOperacionesPropio(false);
        this.CbOpcionesFraccionMixto.setEnabled(false);
        this.CbOpcionesFraccionPropio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnPresentacion = new javax.swing.JPanel();
        JlTitulo = new javax.swing.JLabel();
        LbUniversidad = new javax.swing.JLabel();
        LbCurso = new javax.swing.JLabel();
        LbEstudiante = new javax.swing.JLabel();
        TpContenedor = new javax.swing.JTabbedPane();
        PnFraccionNormal = new javax.swing.JPanel();
        PnAtributoFraccionComun = new javax.swing.JPanel();
        CbSeleccionarFraccionComun = new javax.swing.JComboBox<>();
        LbNumerador = new javax.swing.JLabel();
        LbDenominador = new javax.swing.JLabel();
        TxtDenominador = new javax.swing.JTextField();
        TxtNumerador = new javax.swing.JTextField();
        BtnAceptarFraccionComun = new javax.swing.JButton();
        LbFraccionComun = new javax.swing.JLabel();
        TxtFraccionPropio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CbOpcionesFraccionPropio = new javax.swing.JComboBox<>();
        LbNumeradorOperacionPropio = new javax.swing.JLabel();
        TxtNumeradorOperacionPropio = new javax.swing.JTextField();
        LbDenominadorOperacionPropio = new javax.swing.JLabel();
        TxtDenominadorOperacionPropio = new javax.swing.JTextField();
        BtnOperacionPropio = new javax.swing.JButton();
        LbRespuestaPropio = new javax.swing.JLabel();
        TxtRespuestaPropio = new javax.swing.JTextField();
        PnFraccionMixta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CbSeleccionarFraccionMixto = new javax.swing.JComboBox<>();
        LbNumeradorMixto = new javax.swing.JLabel();
        TxtNumeradorMixto = new javax.swing.JTextField();
        LbDenominadorMixto = new javax.swing.JLabel();
        TxtDenominadorMixto = new javax.swing.JTextField();
        BtnAceptarFraccionMixto = new javax.swing.JButton();
        LbFraccionMixto = new javax.swing.JLabel();
        TxtFraccionMixto = new javax.swing.JTextField();
        LbEnteroMixto = new javax.swing.JLabel();
        TxtEnteroMixto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        CbOpcionesFraccionMixto = new javax.swing.JComboBox<>();
        LbNumeradorOperacionMixto = new javax.swing.JLabel();
        TxtNumeradorOperacionMixto = new javax.swing.JTextField();
        LbDenominadorOperacionMixto = new javax.swing.JLabel();
        TxtDenominadorOperacionMixto = new javax.swing.JTextField();
        BtnOperacionMixto = new javax.swing.JButton();
        LbRespuestaMixto = new javax.swing.JLabel();
        TxtRespuestaMixto = new javax.swing.JTextField();
        LbEnteroOperacionMixto = new javax.swing.JLabel();
        TxtEnteroOperacionMixto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JlTitulo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        JlTitulo.setText("FRACCIONARIO");

        LbUniversidad.setText("Universidad Técnica del Norte");

        LbCurso.setText("Programación Orientada a Objetos");

        LbEstudiante.setText("Ramírez Henry");

        javax.swing.GroupLayout PnPresentacionLayout = new javax.swing.GroupLayout(PnPresentacion);
        PnPresentacion.setLayout(PnPresentacionLayout);
        PnPresentacionLayout.setHorizontalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnPresentacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JlTitulo)
                        .addGap(105, 105, 105)
                        .addComponent(LbUniversidad))
                    .addGroup(PnPresentacionLayout.createSequentialGroup()
                        .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnPresentacionLayout.setVerticalGroup(
            PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPresentacionLayout.createSequentialGroup()
                .addGroup(PnPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlTitulo)
                    .addComponent(LbUniversidad))
                .addGap(18, 18, 18)
                .addComponent(LbCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbEstudiante)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        CbSeleccionarFraccionComun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usar fraccion del Sistema", "Escribir Entero", "Escribir Fraccion" }));
        CbSeleccionarFraccionComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSeleccionarFraccionComunActionPerformed(evt);
            }
        });

        LbNumerador.setText("Numerador:");

        LbDenominador.setText("Denominador:");

        TxtDenominador.setText("0");
        TxtDenominador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDenominadorActionPerformed(evt);
            }
        });

        TxtNumerador.setText("0");
        TxtNumerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeradorActionPerformed(evt);
            }
        });

        BtnAceptarFraccionComun.setText("aceptar");
        BtnAceptarFraccionComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarFraccionComunActionPerformed(evt);
            }
        });

        LbFraccionComun.setText("Fracción Común:");

        TxtFraccionPropio.setEditable(false);
        TxtFraccionPropio.setText("0/0");

        javax.swing.GroupLayout PnAtributoFraccionComunLayout = new javax.swing.GroupLayout(PnAtributoFraccionComun);
        PnAtributoFraccionComun.setLayout(PnAtributoFraccionComunLayout);
        PnAtributoFraccionComunLayout.setHorizontalGroup(
            PnAtributoFraccionComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAtributoFraccionComunLayout.createSequentialGroup()
                .addGroup(PnAtributoFraccionComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnAtributoFraccionComunLayout.createSequentialGroup()
                        .addComponent(CbSeleccionarFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(LbNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(LbDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAceptarFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnAtributoFraccionComunLayout.createSequentialGroup()
                        .addComponent(LbFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFraccionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        PnAtributoFraccionComunLayout.setVerticalGroup(
            PnAtributoFraccionComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAtributoFraccionComunLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PnAtributoFraccionComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbSeleccionarFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumerador)
                    .addComponent(TxtDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDenominador)
                    .addComponent(TxtNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAceptarFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnAtributoFraccionComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFraccionComun)
                    .addComponent(TxtFraccionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CbOpcionesFraccionPropio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operaciones", "Sumar con entero", "Sumar con n/d", "Sumar con objeto fraccion", "Restar con entero", "Restar con n/d", "Restar con objeto fraccion", "Multiplicar con entero", "Multiplicar con n/d", "Multiplicar con objeto fraccion", "Dividir con entero", "Dividir con n/d", "Dividir con objeto fraccion", " " }));
        CbOpcionesFraccionPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbOpcionesFraccionPropioActionPerformed(evt);
            }
        });

        LbNumeradorOperacionPropio.setText("Numerador:");

        TxtNumeradorOperacionPropio.setText("0");
        TxtNumeradorOperacionPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeradorOperacionPropioActionPerformed(evt);
            }
        });

        LbDenominadorOperacionPropio.setText("Denominador:");

        TxtDenominadorOperacionPropio.setText("0");
        TxtDenominadorOperacionPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDenominadorOperacionPropioActionPerformed(evt);
            }
        });

        BtnOperacionPropio.setText("aceptar");
        BtnOperacionPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOperacionPropioActionPerformed(evt);
            }
        });

        LbRespuestaPropio.setText("Respuesta ");

        TxtRespuestaPropio.setEditable(false);
        TxtRespuestaPropio.setText("0/0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbRespuestaPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtRespuestaPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CbOpcionesFraccionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LbNumeradorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNumeradorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbDenominadorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDenominadorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbOpcionesFraccionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumeradorOperacionPropio)
                    .addComponent(TxtNumeradorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDenominadorOperacionPropio)
                    .addComponent(TxtDenominadorOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOperacionPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRespuestaPropio)
                    .addComponent(TxtRespuestaPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnFraccionNormalLayout = new javax.swing.GroupLayout(PnFraccionNormal);
        PnFraccionNormal.setLayout(PnFraccionNormalLayout);
        PnFraccionNormalLayout.setHorizontalGroup(
            PnFraccionNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnFraccionNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnAtributoFraccionComun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnFraccionNormalLayout.setVerticalGroup(
            PnFraccionNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFraccionNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnAtributoFraccionComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TpContenedor.addTab("Fracción Común", PnFraccionNormal);

        CbSeleccionarFraccionMixto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usar fraccion del Sistema", "Escribir Entero", "Escribir Fraccion", "Escribir Fraccion Mixta" }));
        CbSeleccionarFraccionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSeleccionarFraccionMixtoActionPerformed(evt);
            }
        });

        LbNumeradorMixto.setText("Numerador:");

        TxtNumeradorMixto.setText("0");
        TxtNumeradorMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeradorMixtoActionPerformed(evt);
            }
        });

        LbDenominadorMixto.setText("Denominador:");

        TxtDenominadorMixto.setText("0");
        TxtDenominadorMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDenominadorMixtoActionPerformed(evt);
            }
        });

        BtnAceptarFraccionMixto.setText("OK");
        BtnAceptarFraccionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarFraccionMixtoActionPerformed(evt);
            }
        });

        LbFraccionMixto.setText("Fracción Mixta:");

        TxtFraccionMixto.setEditable(false);
        TxtFraccionMixto.setText("0/0");

        LbEnteroMixto.setText("Entero");

        TxtEnteroMixto.setText("0");
        TxtEnteroMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnteroMixtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LbFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CbSeleccionarFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEnteroMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtEnteroMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbNumeradorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumeradorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbDenominadorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDenominadorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAceptarFraccionMixto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbSeleccionarFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAceptarFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDenominadorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDenominadorMixto)
                    .addComponent(TxtNumeradorMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumeradorMixto)
                    .addComponent(LbEnteroMixto)
                    .addComponent(TxtEnteroMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFraccionMixto)
                    .addComponent(TxtFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CbOpcionesFraccionMixto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operaciones", "Sumar con entero", "Sumar con n/d", "Sumar con fraccion Mixta", "Restar con entero", "Restar con n/d", "Restar con fraccion Mixta", "Multiplicar con entero", "Multiplicar con n/d", "Multiplicar con fraccion Mixta", "Dividir con entero", "Dividir con n/d", "Dividir con fraccion Mixta" }));
        CbOpcionesFraccionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbOpcionesFraccionMixtoActionPerformed(evt);
            }
        });

        LbNumeradorOperacionMixto.setText("Numerador:");

        TxtNumeradorOperacionMixto.setText("0");
        TxtNumeradorOperacionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeradorOperacionMixtoActionPerformed(evt);
            }
        });

        LbDenominadorOperacionMixto.setText("Denominador:");

        TxtDenominadorOperacionMixto.setText("0");
        TxtDenominadorOperacionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDenominadorOperacionMixtoActionPerformed(evt);
            }
        });

        BtnOperacionMixto.setText("aceptar");
        BtnOperacionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOperacionMixtoActionPerformed(evt);
            }
        });

        LbRespuestaMixto.setText("Respuesta ");

        TxtRespuestaMixto.setEditable(false);
        TxtRespuestaMixto.setText("0/0");

        LbEnteroOperacionMixto.setText("Entero");

        TxtEnteroOperacionMixto.setText("0");
        TxtEnteroOperacionMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnteroOperacionMixtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbRespuestaMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtRespuestaMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CbOpcionesFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbEnteroOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtEnteroOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbNumeradorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumeradorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbDenominadorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDenominadorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbOpcionesFraccionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumeradorOperacionMixto)
                    .addComponent(TxtNumeradorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDenominadorOperacionMixto)
                    .addComponent(TxtDenominadorOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEnteroOperacionMixto)
                    .addComponent(TxtEnteroOperacionMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRespuestaMixto)
                    .addComponent(TxtRespuestaMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnFraccionMixtaLayout = new javax.swing.GroupLayout(PnFraccionMixta);
        PnFraccionMixta.setLayout(PnFraccionMixtaLayout);
        PnFraccionMixtaLayout.setHorizontalGroup(
            PnFraccionMixtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnFraccionMixtaLayout.setVerticalGroup(
            PnFraccionMixtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFraccionMixtaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TpContenedor.addTab("Fraccion Mixta", PnFraccionMixta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TpContenedor.getAccessibleContext().setAccessibleName("Fraccion Mixta");
        TpContenedor.getAccessibleContext().setAccessibleDescription("mpkmp");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDenominadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDenominadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDenominadorActionPerformed

    private void TxtNumeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeradorActionPerformed

    private void TxtDenominadorOperacionPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDenominadorOperacionPropioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDenominadorOperacionPropioActionPerformed

    private void TxtNumeradorOperacionPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeradorOperacionPropioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeradorOperacionPropioActionPerformed

    private void TxtNumeradorMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeradorMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeradorMixtoActionPerformed

    private void TxtDenominadorMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDenominadorMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDenominadorMixtoActionPerformed

    private void TxtNumeradorOperacionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeradorOperacionMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeradorOperacionMixtoActionPerformed

    private void TxtDenominadorOperacionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDenominadorOperacionMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDenominadorOperacionMixtoActionPerformed

    private void CbSeleccionarFraccionComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSeleccionarFraccionComunActionPerformed
                this.TxtNumerador.setText("0");
        this.TxtDenominador.setText("0");
        this.opcionPropio = this.CbSeleccionarFraccionComun.getSelectedIndex();
        if (opcionPropio == 0) {
            this.RestaurarValoresPropios();
            if (this.fracionPropia1 == null) {
                this.fracionPropia1 = new Fracciones();
                this.CbOpcionesFraccionPropio.setEnabled(true);
            } else {
                this.fracionPropia1.setNumerador(1);
                this.fracionPropia1.setDenominador(1);
                this.CbOpcionesFraccionPropio.setEnabled(true);
            }
            this.TxtFraccionPropio.setText(this.fracionPropia1.Imprimir());
        } else {
            if (this.opcionPropio == 1) {
                this.LbNumerador.setVisible(true);
                this.TxtNumerador.setVisible(true);
                this.BtnAceptarFraccionComun.setVisible(true);
            } else {
                this.LbNumerador.setVisible(true);
                this.TxtNumerador.setVisible(true);
                this.LbDenominador.setVisible(true);
                this.TxtDenominador.setVisible(true);
                this.BtnAceptarFraccionComun.setVisible(true);
            }
        }
    }//GEN-LAST:event_CbSeleccionarFraccionComunActionPerformed

    private void BtnAceptarFraccionComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarFraccionComunActionPerformed
        if (this.opcionPropio == 1) {
            if (this.fracionPropia1 == null) {
                this.fracionPropia1 = new Fracciones(Integer.parseInt(this.TxtNumerador.getText()));
            } else {
                this.fracionPropia1.setDenominador(1);
                this.fracionPropia1.setNumerador(1);
                this.fracionPropia1.setNumerador(Integer.parseInt(this.TxtNumerador.getText()));
            }
            this.TxtFraccionPropio.setText(this.fracionPropia1.Imprimir());
        } else {
            if (this.fracionPropia1 == null) {
                this.fracionPropia1 = new Fracciones(Integer.parseInt(this.TxtNumerador.getText()), Integer.parseInt(this.TxtDenominador.getText()));
            } else {
                this.fracionPropia1.setDenominador(1);
                this.fracionPropia1.setNumerador(1);
                this.fracionPropia1.setNumerador(Integer.parseInt(this.TxtNumerador.getText()));
                this.fracionPropia1.setDenominador(Integer.parseInt(this.TxtDenominador.getText()));
            }
            this.TxtFraccionPropio.setText(this.fracionPropia1.Imprimir());
        }
        this.OcultarRequisitosOperacionesPropio(false);
        this.CbOpcionesFraccionPropio.setEnabled(true);
    }//GEN-LAST:event_BtnAceptarFraccionComunActionPerformed

    private void CbOpcionesFraccionPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbOpcionesFraccionPropioActionPerformed
        this.opcionOperacionPropio = this.CbOpcionesFraccionPropio.getSelectedIndex();
        if (this.opcionOperacionPropio == 0) {
            this.TxtRespuestaPropio.setText("0/0");
            this.OcultarRequisitosOperacionesPropio(false);
        } else {
            if (this.opcionOperacionPropio == 1 || this.opcionOperacionPropio == 4 || this.opcionOperacionPropio == 7 || this.opcionOperacionPropio == 10) {
                this.LbNumeradorOperacionPropio.setVisible(true);
                this.TxtNumeradorOperacionPropio.setVisible(true);
                this.BtnOperacionPropio.setVisible(true);
            } else {
                this.LbNumeradorOperacionPropio.setVisible(true);
                this.TxtNumeradorOperacionPropio.setVisible(true);
                this.LbDenominadorOperacionPropio.setVisible(true);
                this.TxtDenominadorOperacionPropio.setVisible(true);
                this.BtnOperacionPropio.setVisible(true);
            }
        }
    }//GEN-LAST:event_CbOpcionesFraccionPropioActionPerformed

    private void BtnOperacionPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOperacionPropioActionPerformed
        if (this.opcionOperacionPropio == 1) {
            this.fracionPropia1.Sumar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
        } else {
            if (this.opcionOperacionPropio == 2) {
                this.fracionPropia1.Sumar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
            } else {
                if (this.opcionOperacionPropio == 3) {
                    if (this.fraccionPropia2 == null) {
                        this.fraccionPropia2 = new Fracciones(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                        this.fracionPropia1.Sumar(this.fraccionPropia2);
                    } else {
                        this.fraccionPropia2.setNumerador(1);
                        this.fraccionPropia2.setDenominador(1);
                        this.fraccionPropia2.setNumerador(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                        this.fraccionPropia2.setDenominador(Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                        this.fracionPropia1.Sumar(this.fraccionPropia2);
                    }
                } else {
                    if (this.opcionOperacionPropio == 4) {
                        this.fracionPropia1.Restar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                    } else {
                        if (this.opcionOperacionPropio == 5) {
                            this.fracionPropia1.Restar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                        } else {
                            if (this.opcionOperacionPropio == 6) {
                                if (this.fraccionPropia2 == null) {
                                    this.fraccionPropia2 = new Fracciones(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                    this.fracionPropia1.Restar(this.fraccionPropia2);
                                } else {
                                    this.fraccionPropia2.setNumerador(1);
                                    this.fraccionPropia2.setDenominador(1);
                                    this.fraccionPropia2.setNumerador(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                                    this.fraccionPropia2.setDenominador(Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                    this.fracionPropia1.Restar(this.fraccionPropia2);
                                }
                            } else {
                                if (this.opcionOperacionPropio == 7) {
                                    this.fracionPropia1.Multiplicar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                                } else {
                                    if (this.opcionOperacionPropio == 8) {
                                        this.fracionPropia1.Multiplicar(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                    } else {
                                        if (this.opcionOperacionPropio == 9) {
                                            if (this.fraccionPropia2 == null) {
                                                this.fraccionPropia2 = new Fracciones(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                                this.fracionPropia1.Multiplicar(this.fraccionPropia2);
                                            } else {
                                                this.fraccionPropia2.setNumerador(1);
                                                this.fraccionPropia2.setDenominador(1);
                                                this.fraccionPropia2.setNumerador(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                                                this.fraccionPropia2.setDenominador(Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                                this.fracionPropia1.Multiplicar(this.fraccionPropia2);
                                            }
                                        } else {
                                            if (this.opcionOperacionPropio == 10) {
                                                this.fracionPropia1.Dividir(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                                            } else {
                                                if (this.opcionOperacionPropio == 11) {
                                                    this.fracionPropia1.Dividir(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                                } else {
                                                    if (this.fraccionPropia2 == null) {
                                                        this.fraccionPropia2 = new Fracciones(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()), Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                                        this.fracionPropia1.Dividir(this.fraccionPropia2);
                                                    } else {
                                                        this.fraccionPropia2.setNumerador(1);
                                                        this.fraccionPropia2.setDenominador(1);
                                                        this.fraccionPropia2.setNumerador(Integer.parseInt(this.TxtNumeradorOperacionPropio.getText()));
                                                        this.fraccionPropia2.setDenominador(Integer.parseInt(this.TxtDenominadorOperacionPropio.getText()));
                                                        this.fracionPropia1.Dividir(this.fraccionPropia2);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        this.TxtNumeradorOperacionPropio.setText("0");
        this.TxtDenominadorOperacionPropio.setText("0");
        this.OcultarRequisitosOperacionesPropio(false);
        this.TxtRespuestaPropio.setText(this.fracionPropia1.Imprimir());
    }//GEN-LAST:event_BtnOperacionPropioActionPerformed

    private void TxtEnteroMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnteroMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEnteroMixtoActionPerformed

    private void CbSeleccionarFraccionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSeleccionarFraccionMixtoActionPerformed

        this.TxtNumeradorMixto.setText("0");
        this.TxtDenominadorMixto.setText("0");
        this.TxtEnteroMixto.setText("0");
        this.opcionMixto = this.CbSeleccionarFraccionMixto.getSelectedIndex();
        if (this.opcionMixto == 0) {
            this.RestaurarValoresPropios();
            if (this.fraccionMixta1 == null) {
                this.fraccionMixta1 = new FraccionMixtas();
            } else {
                this.fraccionMixta1.setDenominador(1);
                this.fraccionMixta1.setEntero(1);
                this.fraccionMixta1.setNumerador(1);
            }
            this.CbOpcionesFraccionMixto.setEnabled(true);
            this.TxtFraccionMixto.setText(this.fraccionMixta1.Imprimir());
        } else {
            if (this.opcionMixto == 1) {
                this.LbEnteroMixto.setVisible(true);
                this.TxtEnteroMixto.setVisible(true);
                this.BtnAceptarFraccionMixto.setVisible(true);
            } else {
                if (this.opcionMixto == 2) {
                    this.LbNumeradorMixto.setVisible(true);
                    this.TxtNumeradorMixto.setVisible(true);
                    this.LbDenominadorMixto.setVisible(true);
                    this.TxtDenominadorMixto.setVisible(true);
                    this.BtnAceptarFraccionMixto.setVisible(true);
                } else {
                    this.LbEnteroMixto.setVisible(true);
                    this.TxtEnteroMixto.setVisible(true);
                    this.LbNumeradorMixto.setVisible(true);
                    this.TxtNumeradorMixto.setVisible(true);
                    this.LbDenominadorMixto.setVisible(true);
                    this.TxtDenominadorMixto.setVisible(true);
                    this.BtnAceptarFraccionMixto.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_CbSeleccionarFraccionMixtoActionPerformed

    private void BtnAceptarFraccionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarFraccionMixtoActionPerformed
        if (this.opcionMixto == 1) {
            if (this.fraccionMixta1 == null) {
                this.fraccionMixta1 = new FraccionMixtas(Integer.parseInt(this.TxtEnteroMixto.getText()));
            } else {
                this.fraccionMixta1.setDenominador(1);
                this.fraccionMixta1.setEntero(0);
                this.fraccionMixta1.setEntero(Integer.parseInt(this.TxtEnteroMixto.getText()));
            }
            this.TxtFraccionMixto.setText(this.fraccionMixta1.Imprimir());
        } else {
            if (this.opcionMixto == 2) {
                if (this.fraccionMixta1 == null) {
                    this.fraccionMixta1 = new FraccionMixtas(Integer.parseInt(this.TxtNumeradorMixto.getText()), Integer.parseInt(this.TxtDenominadorMixto.getText()));
                } else {
                    this.fraccionMixta1.setDenominador(0);
                    this.fraccionMixta1.setEntero(0);
                    this.fraccionMixta1.setDenominador(Integer.parseInt(this.TxtDenominadorMixto.getText()));
                    this.fraccionMixta1.setNumerador(Integer.parseInt(this.TxtNumeradorMixto.getText()));
                }
                this.TxtFraccionMixto.setText(this.fraccionMixta1.Imprimir());
            } else {
                if (this.fraccionMixta1 == null) {
                    this.fraccionMixta1 = new FraccionMixtas(Integer.parseInt(this.TxtEnteroMixto.getText()), Integer.parseInt(this.TxtNumeradorMixto.getText()), Integer.parseInt(this.TxtDenominadorMixto.getText()));
                } else {
                    this.fraccionMixta1.setDenominador(0);
                    this.fraccionMixta1.setEntero(Integer.parseInt(this.TxtEnteroMixto.getText()));
                    this.fraccionMixta1.setDenominador(Integer.parseInt(this.TxtDenominadorMixto.getText()));
                    this.fraccionMixta1.setNumerador(Integer.parseInt(this.TxtNumeradorMixto.getText()));
                }
                this.TxtFraccionMixto.setText(this.fraccionMixta1.Imprimir());
            }

        }
        this.OcultarRequisitosOperacionesMixto(false);
        this.CbOpcionesFraccionMixto.setEnabled(true);
    }//GEN-LAST:event_BtnAceptarFraccionMixtoActionPerformed

    private void CbOpcionesFraccionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbOpcionesFraccionMixtoActionPerformed
        this.opcionOperacionMixto = this.CbOpcionesFraccionMixto.getSelectedIndex();
        this.OcultarRequisitosOperacionesMixto(false);
        if (this.opcionOperacionMixto == 0) {
            this.TxtRespuestaMixto.setText("0(0/0)");
        } else {
            if (this.opcionOperacionMixto == 1 || this.opcionOperacionMixto == 4 || this.opcionOperacionMixto == 7 || this.opcionOperacionMixto == 10) {
                this.LbEnteroOperacionMixto.setVisible(true);
                this.TxtEnteroOperacionMixto.setVisible(true);
                this.BtnOperacionMixto.setVisible(true);
            } else {
                if (this.opcionOperacionMixto == 2 || this.opcionOperacionMixto == 5 || this.opcionOperacionMixto == 8 || this.opcionOperacionMixto == 11) {
                    this.LbNumeradorOperacionMixto.setVisible(true);
                    this.TxtNumeradorOperacionMixto.setVisible(true);
                    this.LbDenominadorOperacionMixto.setVisible(true);
                    this.TxtDenominadorOperacionMixto.setVisible(true);
                    this.BtnOperacionMixto.setVisible(true);
                } else {
                    this.LbEnteroOperacionMixto.setVisible(true);
                    this.TxtEnteroOperacionMixto.setVisible(true);
                    this.LbNumeradorOperacionMixto.setVisible(true);
                    this.TxtNumeradorOperacionMixto.setVisible(true);
                    this.LbDenominadorOperacionMixto.setVisible(true);
                    this.TxtDenominadorOperacionMixto.setVisible(true);
                    this.BtnOperacionMixto.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_CbOpcionesFraccionMixtoActionPerformed

    private void TxtEnteroOperacionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnteroOperacionMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEnteroOperacionMixtoActionPerformed

    private void BtnOperacionMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOperacionMixtoActionPerformed
        if (this.opcionOperacionMixto == 1) {
            this.fraccionMixta1.Sumar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()));
        } else {
            if (this.opcionOperacionMixto == 2) {
                this.fraccionMixta1.Sumar(Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
            } else {
                if (this.opcionOperacionMixto == 3) {
                    this.fraccionMixta1.Sumar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()), Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                } else {
                    if (this.opcionOperacionMixto == 4) {
                        this.fraccionMixta1.Restar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()));
                    } else {
                        if (this.opcionOperacionMixto == 5) {
                            this.fraccionMixta1.Restar(Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                        } else {
                            if (this.opcionOperacionMixto == 6) {
                                this.fraccionMixta1.Restar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()), Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                            } else {
                                if (this.opcionOperacionMixto == 7) {
                                    this.fraccionMixta1.Multiplicar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()));
                                } else {
                                    if (this.opcionOperacionMixto == 8) {
                                        this.fraccionMixta1.Multiplicar(Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                                    } else {
                                        if (this.opcionOperacionMixto == 9) {
                                            this.fraccionMixta1.Multiplicar(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()), Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                                        } else {
                                            if (this.opcionOperacionMixto == 10) {
                                                this.fraccionMixta1.Dividir(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()));
                                            } else {
                                                if (this.opcionOperacionMixto == 11) {
                                                    this.fraccionMixta1.Dividir(Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                                                } else {
                                                    this.fraccionMixta1.Dividir(Integer.parseInt(this.TxtEnteroOperacionMixto.getText()), Integer.parseInt(this.TxtNumeradorOperacionMixto.getText()), Integer.parseInt(this.TxtDenominadorOperacionMixto.getText()));
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        this.TxtRespuestaMixto.setText(this.fraccionMixta1.Imprimir());
    }//GEN-LAST:event_BtnOperacionMixtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public void RestaurarValoresMixtos() {
        this.TxtNumeradorMixto.setText("0");
        this.TxtDenominadorMixto.setText("0");
        this.TxtNumeradorOperacionMixto.setText("0");
        this.TxtDenominadorOperacionMixto.setText("0");
        this.TxtFraccionMixto.setText("0/0");
        this.TxtRespuestaMixto.setText("0/0");
    }

    public void RestaurarValoresPropios() {
        this.TxtNumerador.setText("0");
        this.TxtDenominador.setText("0");
        this.TxtNumeradorOperacionPropio.setText("0");
        this.TxtDenominadorOperacionPropio.setText("0");
        this.TxtFraccionPropio.setText("0/0");
        this.TxtRespuestaPropio.setText("0/0");
    }

    public void OcultarRequisitosOperacionesMixto(boolean mostrar) {
        this.LbDenominadorOperacionMixto.setVisible(mostrar);
        this.LbNumeradorOperacionMixto.setVisible(mostrar);
        this.TxtDenominadorOperacionMixto.setVisible(mostrar);
        this.TxtNumeradorOperacionMixto.setVisible(mostrar);
        this.LbDenominadorMixto.setVisible(mostrar);
        this.LbNumeradorMixto.setVisible(mostrar);
        this.TxtNumeradorMixto.setVisible(mostrar);
        this.TxtDenominadorMixto.setVisible(mostrar);
        this.BtnAceptarFraccionMixto.setVisible(mostrar);
        this.BtnOperacionMixto.setVisible(mostrar);
        this.LbEnteroMixto.setVisible(mostrar);
        this.TxtEnteroMixto.setVisible(mostrar);
        this.LbEnteroOperacionMixto.setVisible(mostrar);
        this.TxtEnteroOperacionMixto.setVisible(mostrar);
    }

    public void OcultarRequisitosOperacionesPropio(boolean mostrar) {
        this.LbDenominadorOperacionPropio.setVisible(mostrar);
        this.LbNumeradorOperacionPropio.setVisible(mostrar);
        this.TxtDenominadorOperacionPropio.setVisible(mostrar);
        this.TxtNumeradorOperacionPropio.setVisible(mostrar);
        this.LbDenominador.setVisible(mostrar);
        this.LbNumerador.setVisible(mostrar);
        this.TxtNumerador.setVisible(mostrar);
        this.TxtDenominador.setVisible(mostrar);
        this.BtnOperacionPropio.setVisible(mostrar);
        this.BtnAceptarFraccionComun.setVisible(mostrar);
    }

    int opcionPropio, opcionMixto, opcionOperacionPropio, opcionOperacionMixto;
    Fracciones fracionPropia1, fraccionPropia2;
    FraccionMixtas fraccionMixta1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarFraccionComun;
    private javax.swing.JButton BtnAceptarFraccionMixto;
    private javax.swing.JButton BtnOperacionMixto;
    private javax.swing.JButton BtnOperacionPropio;
    private javax.swing.JComboBox<String> CbOpcionesFraccionMixto;
    private javax.swing.JComboBox<String> CbOpcionesFraccionPropio;
    private javax.swing.JComboBox<String> CbSeleccionarFraccionComun;
    private javax.swing.JComboBox<String> CbSeleccionarFraccionMixto;
    private javax.swing.JLabel JlTitulo;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbDenominador;
    private javax.swing.JLabel LbDenominadorMixto;
    private javax.swing.JLabel LbDenominadorOperacionMixto;
    private javax.swing.JLabel LbDenominadorOperacionPropio;
    private javax.swing.JLabel LbEnteroMixto;
    private javax.swing.JLabel LbEnteroOperacionMixto;
    private javax.swing.JLabel LbEstudiante;
    private javax.swing.JLabel LbFraccionComun;
    private javax.swing.JLabel LbFraccionMixto;
    private javax.swing.JLabel LbNumerador;
    private javax.swing.JLabel LbNumeradorMixto;
    private javax.swing.JLabel LbNumeradorOperacionMixto;
    private javax.swing.JLabel LbNumeradorOperacionPropio;
    private javax.swing.JLabel LbRespuestaMixto;
    private javax.swing.JLabel LbRespuestaPropio;
    private javax.swing.JLabel LbUniversidad;
    private javax.swing.JPanel PnAtributoFraccionComun;
    private javax.swing.JPanel PnFraccionMixta;
    private javax.swing.JPanel PnFraccionNormal;
    private javax.swing.JPanel PnPresentacion;
    private javax.swing.JTabbedPane TpContenedor;
    private javax.swing.JTextField TxtDenominador;
    private javax.swing.JTextField TxtDenominadorMixto;
    private javax.swing.JTextField TxtDenominadorOperacionMixto;
    private javax.swing.JTextField TxtDenominadorOperacionPropio;
    private javax.swing.JTextField TxtEnteroMixto;
    private javax.swing.JTextField TxtEnteroOperacionMixto;
    private javax.swing.JTextField TxtFraccionMixto;
    private javax.swing.JTextField TxtFraccionPropio;
    private javax.swing.JTextField TxtNumerador;
    private javax.swing.JTextField TxtNumeradorMixto;
    private javax.swing.JTextField TxtNumeradorOperacionMixto;
    private javax.swing.JTextField TxtNumeradorOperacionPropio;
    private javax.swing.JTextField TxtRespuestaMixto;
    private javax.swing.JTextField TxtRespuestaPropio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
